const path = require("path");
const fs = require("fs");
const esbuild = require("esbuild");

const isWatch = process.argv.includes("--watch");
const srcEntry = path.join(__dirname, "src", "index.js");
const outBundle = path.join(__dirname, "dist", "nexa-editor.bundle.js");
const outPluginHtml = path.join(__dirname, "lib", "nexa-plugin.html");
// Plain-<script> bundles next to the editor bundle (all build OUTPUT in
// dist/, gitignored, rebuilt by `npm run build`):
//   dist/nexa-sdk.bundle.js      Lit (window.NEXA_LIT) + the component SDK
//                                (NEXA.component, NexaElement, NexaField, codecs).
//                                Editor AND deployed pages. See src/sdk/runtime-entry.js.
//   dist/nexa-sdk-kit.bundle.js  the property kit (nx-* widgets + schema ->
//                                inspector renderer). Editor only; uses the SDK
//                                bundle's Lit through window.NEXA_LIT (see the
//                                "lit" alias below) instead of a second copy.
// Plus lib/nexa-registry-client.js (the deployed page's /nexa/_registry.js),
// generated from src/sdk/registry.js — the same registry the editor bundles.
const sdkEntry = path.join(__dirname, "src", "sdk", "runtime-entry.js");
const outSdkBundle = path.join(__dirname, "dist", "nexa-sdk.bundle.js");
const kitEntry = path.join(__dirname, "src", "sdk", "kit", "index.js");
const outKitBundle = path.join(__dirname, "dist", "nexa-sdk-kit.bundle.js");
const registryEntry = path.join(__dirname, "src", "sdk", "registry-entry.js");
const outRegistryClient = path.join(__dirname, "lib", "nexa-registry-client.js");
// lib/nexa-model.js — the node tree model (src/model/) as CommonJS, so the
// screen worker migrates pre-tree projects exactly the way the editor does.
const modelEntry = path.join(__dirname, "src", "model", "index.js");
const outModel = path.join(__dirname, "lib", "nexa-model.js");

// Resolves `import ... from "lit"` to the global the SDK bundle publishes.
const litFromGlobal = {
    name: "lit-from-global",
    setup(build) {
        build.onResolve({ filter: /^lit$/ }, () => ({ path: path.join(__dirname, "src", "sdk", "kit", "lit-global.js") }));
    }
};

async function bundle(entry, extra) {
    const result = await esbuild.build(Object.assign({
        entryPoints: [entry],
        bundle: true,
        format: "iife",
        write: false,
        target: ["es2020"]
    }, extra || {}));
    return result.outputFiles[0].text;
}

async function runBuild() {
    const startTime = Date.now();
    try {
        const result = await esbuild.build({
            entryPoints: [srcEntry],
            bundle: true,
            format: "iife",
            write: false,
            target: ["es2020"]
        });

        const code = result.outputFiles[0].text;

        // Ensure dist folder exists
        const distDir = path.join(__dirname, "dist");
        if (!fs.existsSync(distDir)) {
            fs.mkdirSync(distDir, { recursive: true });
        }
        fs.writeFileSync(outBundle, code, "utf8");

        // Write wrapped lib/nexa-plugin.html. This file MUST live in lib/,
        // next to lib/nexa-plugin.js — Node-RED's own plugin loader derives
        // the .html filename by swapping the .js extension on the exact
        // registered plugin path (@node-red/registry/lib/loader.js), so
        // there is no way to serve it from anywhere else. The SDK bundle
        // (Lit + component SDK) and the property kit are plain <script src>s
        // (served via RED.httpAdmin — see lib/nexa-plugin.js) placed BEFORE
        // the editor's own script block, rather than folded into it — see
        // src/sdk/runtime-entry.js's comment for why. (test/run-all.js
        // extracts that script block, so it must stay the last one.)
        const htmlBanner = "<!-- AUTO-GENERATED by build.js from src/index.js — DO NOT EDIT THIS FILE.\n" +
            "     Edit the modular source files under src/ instead, then run npm run build\n" +
            "     (or npm run watch). Lives here, not in dist/, because Node-RED's plugin\n" +
            "     loader requires a plugin's .html file to sit next to its registered .js\n" +
            "     file (lib/nexa-plugin.js) — that pairing is not configurable. -->\n";
        const htmlContent = `${htmlBanner}<script src="nexa-dashboard/_sdk.js"></script>\n<script src="nexa-dashboard/_sdk-kit.js"></script>\n<script type="text/javascript">\n// Auto-generated by build.js — DO NOT EDIT MANUALLY.\n// Edit modular source files in src/ instead.\n${code}\n</script>\n`;
        fs.writeFileSync(outPluginHtml, htmlContent, "utf8");

        const banner = function (src) {
            return "// AUTO-GENERATED by build.js from " + src + " — DO NOT EDIT THIS FILE.\n" +
                "// Edit the source instead, then run `npm run build` (or `npm run watch`).\n";
        };
        fs.writeFileSync(outSdkBundle, banner("src/sdk/runtime-entry.js") + await bundle(sdkEntry), "utf8");
        // The editor runs plugin <script src>s in no guaranteed order, so the
        // kit may arrive before the SDK it takes Lit from: it then waits in
        // window.__nexaSdkReady, which src/sdk/runtime-entry.js drains.
        const kitCode = await bundle(kitEntry, { plugins: [litFromGlobal] });
        fs.writeFileSync(outKitBundle, banner("src/sdk/kit/index.js") +
            "(function () {\nfunction nexaKitInit() {\n" + kitCode + "}\n" +
            "if (window.NEXA_LIT) nexaKitInit(); else (window.__nexaSdkReady = window.__nexaSdkReady || []).push(nexaKitInit);\n})();\n", "utf8");
        fs.writeFileSync(outRegistryClient, banner("src/sdk/registry-entry.js") +
            "// Served to deployed pages as /nexa/_registry.js (lib/screen-worker.js).\n" + await bundle(registryEntry), "utf8");

        fs.writeFileSync(outModel, banner("src/model/index.js") + await bundle(modelEntry, { format: "cjs", platform: "node" }), "utf8");

        console.log(`[build] Built nexa-plugin.html, nexa-editor.bundle.js, nexa-sdk.bundle.js, nexa-sdk-kit.bundle.js nexa-registry-client.js & nexa-model.js in ${Date.now() - startTime}ms`);
    } catch (e) {
        console.error("[build] Build error:", e);
    }
}

if (isWatch) {
    runBuild().then(() => {
        console.log("[build] Watching src/ for changes...");
        const srcDir = path.join(__dirname, "src");
        fs.watch(srcDir, { recursive: true }, (eventType, filename) => {
            if (filename && (filename.endsWith(".js") || filename.endsWith(".html"))) {
                console.log(`[build] Change detected in ${filename}, rebuilding...`);
                runBuild();
            }
        });
    });
} else {
    runBuild();
}
