const path = require("path");
const fs = require("fs");
const esbuild = require("esbuild");

const isWatch = process.argv.includes("--watch");
const srcEntry = path.join(__dirname, "src", "index.js");
const outBundle = path.join(__dirname, "dist", "nexa-editor.bundle.js");
const outPluginHtml = path.join(__dirname, "lib", "nexa-plugin.html");
// Standalone Lit vendor bundle for the editor AND deployed public pages
// (nexa-runtime-client.js is hand-maintained plain JS, not part of the src/
// esbuild pipeline, so it needs Lit as a separately-served <script> — see
// src/lit-vendor.js's own comment for why this can't just be an ES import at
// evaluation time). Lives in dist/ (build OUTPUT, gitignored, rebuilt by
// `npm run build`) rather than lib/ — unlike nexa-plugin.html, nothing forces
// this one to sit next to nexa-plugin.js, so it goes wherever every other
// generated artifact goes, to keep lib/ readable as "hand-written source" at
// a glance (see lib/nexa-plugin.js's two res.sendFile(...) calls that serve
// it from here).
const litVendorEntry = path.join(__dirname, "src", "lit-vendor.js");
const outLitVendorBundle = path.join(__dirname, "dist", "nexa-lit-vendor.bundle.js");

async function runBuild() {
    const startTime = Date.now();
    try {
        const result = await esbuild.build({
            entryPoints: [srcEntry],
            bundle: true,
            format: "iife",
            write: false,
            target: ["es2020"]
        });

        const code = result.outputFiles[0].text;

        // Ensure dist folder exists
        const distDir = path.join(__dirname, "dist");
        if (!fs.existsSync(distDir)) {
            fs.mkdirSync(distDir, { recursive: true });
        }
        fs.writeFileSync(outBundle, code, "utf8");

        // Write wrapped lib/nexa-plugin.html. This file MUST live in lib/,
        // next to lib/nexa-plugin.js — Node-RED's own plugin loader derives
        // the .html filename by swapping the .js extension on the exact
        // registered plugin path (@node-red/registry/lib/loader.js), so
        // there is no way to serve it from anywhere else. The Lit vendor
        // bundle is a plain <script src> (served via RED.httpAdmin — see
        // lib/nexa-plugin.js) rather than folded into the bundle below — see
        // src/lit-vendor.js's comment for why.
        const htmlBanner = "<!-- AUTO-GENERATED by build.js from src/index.js — DO NOT EDIT THIS FILE.\n" +
            "     Edit the modular source files under src/ instead, then run npm run build\n" +
            "     (or npm run watch). Lives here, not in dist/, because Node-RED's plugin\n" +
            "     loader requires a plugin's .html file to sit next to its registered .js\n" +
            "     file (lib/nexa-plugin.js) — that pairing is not configurable. -->\n";
        const htmlContent = `${htmlBanner}<script src="nexa-dashboard/_lit-vendor.js"></script>\n<script type="text/javascript">\n// Auto-generated by build.js — DO NOT EDIT MANUALLY.\n// Edit modular source files in src/ instead.\n${code}\n</script>\n`;
        fs.writeFileSync(outPluginHtml, htmlContent, "utf8");

        const litVendorResult = await esbuild.build({
            entryPoints: [litVendorEntry],
            bundle: true,
            format: "iife",
            write: false,
            target: ["es2020"]
        });
        const litVendorBanner = "// AUTO-GENERATED by build.js from src/lit-vendor.js — DO NOT EDIT THIS FILE.\n" +
            "// Edit src/lit-vendor.js instead, then run `npm run build` (or `npm run watch`).\n" +
            "// Served by lib/nexa-plugin.js to both the editor (RED.httpAdmin) and\n" +
            "// deployed public pages (RED.httpNode, under /nexa/_lit-vendor.js).\n";
        fs.writeFileSync(outLitVendorBundle, litVendorBanner + litVendorResult.outputFiles[0].text, "utf8");

        console.log(`[build] Built nexa-plugin.html, nexa-editor.bundle.js & nexa-lit-vendor.bundle.js in ${Date.now() - startTime}ms`);
    } catch (e) {
        console.error("[build] Build error:", e);
    }
}

if (isWatch) {
    runBuild().then(() => {
        console.log("[build] Watching src/ for changes...");
        const srcDir = path.join(__dirname, "src");
        fs.watch(srcDir, { recursive: true }, (eventType, filename) => {
            if (filename && (filename.endsWith(".js") || filename.endsWith(".html"))) {
                console.log(`[build] Change detected in ${filename}, rebuilding...`);
                runBuild();
            }
        });
    });
} else {
    runBuild();
}
