const path = require("path");
const fs = require("fs");
const esbuild = require("esbuild");

const isWatch = process.argv.includes("--watch");
const srcEntry = path.join(__dirname, "src", "index.js");
const distDir = path.join(__dirname, "dist");

// All build outputs live in dist/ (100% autogenerated):
const outBundle = path.join(distDir, "nexa-editor.bundle.js");
const outPluginHtml = path.join(distDir, "nexa-plugin.html");
const outPluginJs = path.join(distDir, "nexa-plugin.js");
const sdkEntry = path.join(__dirname, "src", "sdk", "runtime-entry.js");
const outSdkBundle = path.join(distDir, "nexa-sdk.bundle.js");
const kitEntry = path.join(__dirname, "src", "sdk", "kit", "index.js");
const outKitBundle = path.join(distDir, "nexa-sdk-kit.bundle.js");
const registryEntry = path.join(__dirname, "src", "sdk", "registry-entry.js");
const outRegistryClient = path.join(distDir, "nexa-registry-client.js");
const modelEntry = path.join(__dirname, "src", "model", "index.js");
const outModel = path.join(distDir, "nexa-model.js");
const outModelClient = path.join(distDir, "nexa-model-client.js");
const runtimeEntry = path.join(__dirname, "src", "runtime", "index.js");
const outRuntimeBundle = path.join(distDir, "nexa-runtime.bundle.js");

// Resolves `import ... from "lit"` to the global the SDK bundle publishes.
const litFromGlobal = {
    name: "lit-from-global",
    setup(build) {
        build.onResolve({ filter: /^lit$/ }, () => ({ path: path.join(__dirname, "src", "sdk", "kit", "lit-global.js") }));
    }
};

async function bundle(entry, extra) {
    const result = await esbuild.build(Object.assign({
        entryPoints: [entry],
        bundle: true,
        format: "iife",
        write: false,
        target: ["es2020"]
    }, extra || {}));
    return result.outputFiles[0].text;
}

async function runBuild() {
    const startTime = Date.now();
    try {
        if (!fs.existsSync(distDir)) {
            fs.mkdirSync(distDir, { recursive: true });
        }

        const result = await esbuild.build({
            entryPoints: [srcEntry],
            bundle: true,
            format: "iife",
            write: false,
            target: ["es2020"]
        });

        const code = result.outputFiles[0].text;
        fs.writeFileSync(outBundle, code, "utf8");

        // Write wrapped dist/nexa-plugin.html next to dist/nexa-plugin.js
        // for Node-RED's plugin registry loader.
        const htmlBanner = "<!-- AUTO-GENERATED by build.js from src/index.js — DO NOT EDIT THIS FILE.\n" +
            "     Edit modular source files under src/ instead, then run npm run build.\n" +
            "     Pairing required by Node-RED plugin loader (sits next to dist/nexa-plugin.js). -->\n";
        const htmlContent = `${htmlBanner}<script src="nexa-dashboard/_sdk.js"></script>\n<script src="nexa-dashboard/_sdk-kit.js"></script>\n<script type="module" src="nexa-dashboard-media/vendor/media.js"></script>\n<script type="module" src="nexa-dashboard-layout/vendor/layout.js"></script>\n<script type="text/javascript">\n// Auto-generated by build.js — DO NOT EDIT MANUALLY.\n// Edit modular source files in src/ instead.\n${code}\n</script>\n`;
        fs.writeFileSync(outPluginHtml, htmlContent, "utf8");

        // Bridge plugin entry for Node-RED loader
        fs.writeFileSync(outPluginJs, '// AUTO-GENERATED by build.js — DO NOT EDIT.\nmodule.exports = require("../src/server/plugin.js");\n', "utf8");

        const banner = function (src) {
            return "// AUTO-GENERATED by build.js from " + src + " — DO NOT EDIT THIS FILE.\n" +
                "// Edit the source instead, then run `npm run build` (or `npm run watch`).\n";
        };

        // Minified SDK bundle (Lit + Nexa SDK core)
        fs.writeFileSync(outSdkBundle, banner("src/sdk/runtime-entry.js") + await bundle(sdkEntry, { minify: true }), "utf8");

        // Property kit bundle (Inspector widgets)
        const kitCode = await bundle(kitEntry, { plugins: [litFromGlobal] });
        fs.writeFileSync(outKitBundle, banner("src/sdk/kit/index.js") +
            "(function () {\nfunction nexaKitInit() {\n" + kitCode + "}\n" +
            "if (window.NEXA_LIT) nexaKitInit(); else (window.__nexaSdkReady = window.__nexaSdkReady || []).push(nexaKitInit);\n})();\n", "utf8");

        // Registry client bundle
        fs.writeFileSync(outRegistryClient, banner("src/sdk/registry-entry.js") +
            "// Served to deployed pages as /nexa/_registry.js.\n" + await bundle(registryEntry), "utf8");

        // Model CommonJS for Node-RED / workers / tests
        fs.writeFileSync(outModel, banner("src/model/index.js") + await bundle(modelEntry, { format: "cjs", platform: "node" }), "utf8");

        // Model IIFE for deployed browser pages
        fs.writeFileSync(outModelClient, banner("src/model/index.js") +
            "// Served to deployed pages as /nexa/_model.js.\n" + await bundle(modelEntry, { globalName: "NexaModel" }), "utf8");

        // Single unified runtime client bundle
        const runtimeCode = await bundle(runtimeEntry, { format: "iife" });
        fs.writeFileSync(outRuntimeBundle, banner("src/runtime/index.js") +
            "// Modular runtime client bundle for Nexa Dashboard (served as /nexa/_runtime.js).\n" + runtimeCode, "utf8");

        console.log(`[build] Built dist artifacts (editor, plugin HTML/JS, runtime, SDK, kit, model, registry) in ${Date.now() - startTime}ms`);
    } catch (e) {
        console.error("[build] Build error:", e);
    }
}

if (isWatch) {
    runBuild().then(() => {
        console.log("[build] Watching src/ for changes...");
        const srcDir = path.join(__dirname, "src");
        fs.watch(srcDir, { recursive: true }, (eventType, filename) => {
            if (filename && (filename.endsWith(".js") || filename.endsWith(".html"))) {
                console.log(`[build] Change detected in ${filename}, rebuilding...`);
                runBuild();
            }
        });
    });
} else {
    runBuild();
}
