// Entry of lib/nexa-registry-client.js (generated by build.js) — the deployed
// page's /nexa/_registry.js. Same registry as the editor and the SDK bundle.
import { ensureRegistry } from "./registry.js";

ensureRegistry();
