// AUTO-GENERATED by build.js from src/model/index.js — DO NOT EDIT THIS FILE.
// Edit the source instead, then run `npm run build` (or `npm run watch`).
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/model/index.js
var index_exports = {};
__export(index_exports, {
  BindingRef: () => BindingRef,
  CAROUSEL_DEFAULT: () => CAROUSEL_DEFAULT,
  CONTAINER_TYPES: () => CONTAINER_TYPES,
  DEFAULT_BREAKPOINTS: () => DEFAULT_BREAKPOINTS,
  DEFAULT_THEME: () => DEFAULT_THEME,
  DEVICE_PRESETS: () => DEVICE_PRESETS,
  H_CONSTRAINTS: () => H_CONSTRAINTS,
  ITEMS_DEFAULT: () => ITEMS_DEFAULT,
  LAYOUT_MODES: () => LAYOUT_MODES,
  NAME_RE: () => NAME_RE,
  OVERLAY_DEFAULT: () => OVERLAY_DEFAULT,
  OVERLAY_KINDS: () => OVERLAY_KINDS,
  OVERRIDABLE: () => OVERRIDABLE,
  PLACES: () => PLACES,
  SHADES: () => SHADES,
  TEMPLATE_CONTENT_MODES: () => TEMPLATE_CONTENT_MODES,
  TEMPLATE_LIVE_DEFAULT: () => TEMPLATE_LIVE_DEFAULT,
  TOKEN_CATEGORIES: () => TOKEN_CATEGORIES,
  TREE_VERSION: () => TREE_VERSION,
  V_CONSTRAINTS: () => V_CONSTRAINTS,
  ZOOM_DEFAULT: () => ZOOM_DEFAULT,
  absBox: () => absBox,
  activeBreakpoint: () => activeBreakpoint,
  alignFraction: () => alignFraction,
  allDeclarations: () => allDeclarations,
  allNodes: () => allNodes,
  ancestors: () => ancestors,
  applyFallbacks: () => applyFallbacks,
  applyOverrides: () => applyOverrides,
  bandOf: () => bandOf,
  baseOf: () => baseOf,
  borderOf: () => borderOf,
  boxCss: () => boxCss,
  breakpointsOf: () => breakpointsOf,
  buildInstance: () => buildInstance,
  canRotate: () => canRotate,
  carouselOf: () => carouselOf,
  carouselSlideSize: () => carouselSlideSize,
  carouselTrackCss: () => carouselTrackCss,
  chainFor: () => chainFor,
  childBounds: () => childBounds,
  childSizing: () => childSizing,
  cloneWithNewIds: () => cloneWithNewIds,
  constraintCss: () => constraintCss,
  constraintsOf: () => constraintsOf,
  contentOrigin: () => contentOrigin,
  currentTheme: () => currentTheme,
  designBreakpoint: () => designBreakpoint,
  detach: () => detach,
  dockOf: () => dockOf,
  effectiveLocked: () => effectiveLocked,
  effectiveVisibility: () => effectiveVisibility,
  find: () => find,
  findByName: () => findByName,
  findType: () => findType,
  fitGroup: () => fitGroup,
  flowAxis: () => flowAxis,
  frameCss: () => frameCss,
  frameHugs: () => frameHugs,
  generatePalette: () => generatePalette,
  getTypes: () => getTypes,
  guessConstraints: () => guessConstraints,
  hasAutoLayout: () => hasAutoLayout,
  hasConstraints: () => hasConstraints,
  hasOverrides: () => hasOverrides,
  hasVariables: () => hasVariables,
  inSlot: () => inSlot,
  inferNodeConstraints: () => inferNodeConstraints,
  innerSize: () => innerSize,
  insert: () => insert,
  isAncestor: () => isAncestor,
  isBindingRef: () => isBindingRef,
  isContainer: () => isContainer,
  isInFlow: () => isInFlow,
  isNoValue: () => isNoValue,
  isSlotFrame: () => isSlotFrame,
  isSlotHost: () => isSlotHost,
  isTokenRef: () => isTokenRef,
  isTypeRef: () => isTypeRef,
  kids: () => kids,
  layoutOf: () => layoutOf,
  listTokens: () => listTokens,
  locate: () => locate,
  makeFrame: () => makeFrame,
  makeScope: () => makeScope,
  marginOf: () => marginOf,
  memberAt: () => memberAt,
  memberPaths: () => memberPaths,
  mentionsToken: () => mentionsToken,
  migrateOverrideKeys: () => migrateOverrideKeys,
  migrateProject: () => migrateProject,
  migrateSurface: () => migrateSurface,
  move: () => move,
  onScreen: () => onScreen,
  overlayBox: () => overlayBox,
  overlayOf: () => overlayOf,
  overrideDiff: () => overrideDiff,
  overrideOf: () => overrideOf,
  paddingOf: () => paddingOf,
  parentOf: () => parentOf,
  parentSize: () => parentSize,
  placeOf: () => placeOf,
  placeOrphan: () => placeOrphan,
  previewWidthOf: () => previewWidthOf,
  rangeOf: () => rangeOf,
  refitGroupsUp: () => refitGroupsUp,
  remove: () => remove,
  resizeWithConstraints: () => resizeWithConstraints,
  resolveNode: () => resolveNode,
  resolveToken: () => resolveToken,
  resolveTokenProps: () => resolveTokenProps,
  resolveTokenValue: () => resolveTokenValue,
  setTheme: () => setTheme,
  setTypes: () => setTypes,
  slotOf: () => slotOf,
  styleOf: () => styleOf,
  surfaceScope: () => surfaceScope,
  syncSlots: () => syncSlots,
  takesPadding: () => takesPadding,
  templateContentFit: () => templateContentFit,
  templateContentOf: () => templateContentOf,
  templateLiveOf: () => templateLiveOf,
  themeCss: () => themeCss,
  themeOf: () => themeOf,
  tidyContainer: () => tidyContainer,
  tokenCss: () => tokenCss,
  tokenPathOf: () => tokenPathOf,
  tokenVar: () => tokenVar,
  tokenVarName: () => tokenVarName,
  tracksCss: () => tracksCss,
  unwrap: () => unwrap,
  variableValue: () => variableValue,
  visibleVariables: () => visibleVariables,
  walk: () => walk,
  wrapIn: () => wrapIn,
  wrapInGroup: () => wrapInGroup,
  zOf: () => zOf,
  zoomOf: () => zoomOf
});
module.exports = __toCommonJS(index_exports);

// src/model/tree.js
var CONTAINER_TYPES = { "@group": true, "@frame": true };
function isContainer(node) {
  return !!(node && (CONTAINER_TYPES[node.type] || isSlotHost(node)));
}
function isSlotHost(node) {
  return !!(node && node.slots === true && !CONTAINER_TYPES[node.type]);
}
function isSlotFrame(node) {
  return !!(node && node.type === "@frame" && typeof node.inSlot === "string" && node.inSlot !== "");
}
function slotFrame(slot, genId) {
  return {
    id: genId(),
    type: "@frame",
    inSlot: slot.name,
    slotLabel: slot.label || slot.name,
    x: 0,
    y: 0,
    w: 0,
    h: 0,
    children: [],
    layout: Object.assign({ mode: "vertical", padding: { t: 16, r: 16, b: 16, l: 16 }, gap: 8 }, slot.layout || {}),
    style: { fill: "", stroke: "", strokeWidth: 0, radius: 0, clip: true }
  };
}
function syncSlots(node, slots, genId) {
  if (!node || CONTAINER_TYPES[node.type]) return false;
  var changed = false;
  if (node.slots !== true) {
    node.slots = true;
    changed = true;
  }
  var list = node.children || (node.children = []);
  var byName = {};
  list.forEach(function(c) {
    if (isSlotFrame(c) && !byName[c.inSlot]) byName[c.inSlot] = c;
  });
  var ordered = [];
  (slots || []).forEach(function(slot) {
    if (!slot || slot.name === void 0 || slot.name === null || slot.name === "") return;
    var name = String(slot.name);
    var f = byName[name];
    if (!f) {
      f = slotFrame({ name, label: slot.label, layout: slot.layout }, genId);
      changed = true;
    }
    var label = slot.label || name;
    if (f.slotLabel !== label) {
      f.slotLabel = label;
      changed = true;
    }
    if (f.slotUnused) {
      delete f.slotUnused;
      changed = true;
    }
    delete byName[name];
    ordered.push(f);
  });
  list.forEach(function(c) {
    if (ordered.indexOf(c) !== -1) return;
    if (isSlotFrame(c) && !c.slotUnused) {
      c.slotUnused = true;
      changed = true;
    }
    ordered.push(c);
  });
  if (ordered.length !== list.length || ordered.some(function(c, i) {
    return c !== list[i];
  })) changed = true;
  node.children = ordered;
  return changed;
}
function slotOf(node, name) {
  return kids(node).filter(function(c) {
    return isSlotFrame(c) && c.inSlot === String(name);
  })[0] || null;
}
function kids(node) {
  return node && node.children || [];
}
function listOf(surface, parent) {
  if (!parent) return surface.components || (surface.components = []);
  return parent.children || (parent.children = []);
}
function walk(surface, fn, opts) {
  var stop = false;
  function visit(list, parent, depth) {
    for (var i = 0; i < list.length && !stop; i++) {
      var node = list[i];
      var r = fn(node, parent, i, depth);
      if (r === "stop") {
        stop = true;
        return;
      }
      if (r !== false && node.children) visit(node.children, node, depth + 1);
    }
  }
  visit(surface && surface.components || [], null, 0);
  if (opts && opts.orphans && surface && surface.orphans) visit(surface.orphans, null, 0);
}
function allNodes(surface, opts) {
  var out = [];
  walk(surface, function(n) {
    out.push(n);
  }, opts);
  return out;
}
function locate(surface, id) {
  var found = null;
  function search(list, parent, orphan) {
    for (var i = 0; i < list.length; i++) {
      var n = list[i];
      if (n.id === id) {
        found = { node: n, parent, list, index: i, orphan };
        return true;
      }
      if (n.children && search(n.children, n, orphan)) return true;
    }
    return false;
  }
  if (!surface) return null;
  if (!search(surface.components || [], null, false) && surface.orphans) search(surface.orphans, null, true);
  return found;
}
function find(surface, id) {
  var loc = locate(surface, id);
  return loc ? loc.node : null;
}
function parentOf(surface, id) {
  var loc = locate(surface, id);
  return loc ? loc.parent : null;
}
function ancestors(surface, id) {
  var chain = [];
  var loc = locate(surface, id);
  while (loc && loc.parent) {
    chain.unshift(loc.parent);
    loc = locate(surface, loc.parent.id);
  }
  return chain;
}
function isAncestor(surface, ancestorId, id) {
  return ancestors(surface, id).some(function(a) {
    return a.id === ancestorId;
  });
}
function insert(surface, parentId, index, node) {
  var parent = parentId ? find(surface, parentId) : null;
  if (parentId && !isContainer(parent)) throw new Error("[nexa] insert: " + parentId + " is not a container");
  if (parent && isSlotHost(parent) && !(isSlotFrame(node) && !slotOf(parent, node.inSlot))) throw new Error("[nexa] it goes into one of the component's slots (a panel), not into the component itself");
  var list = listOf(surface, parent);
  var at = index === void 0 || index === null || index > list.length ? list.length : Math.max(0, index);
  list.splice(at, 0, node);
  return node;
}
function detach(surface, id) {
  var loc = locate(surface, id);
  if (!loc) return null;
  loc.list.splice(loc.index, 1);
  return { node: loc.node, parentId: loc.parent ? loc.parent.id : null, index: loc.index, orphan: loc.orphan };
}
function move(surface, id, parentId, index) {
  if (parentId && (parentId === id || isAncestor(surface, id, parentId))) throw new Error("[nexa] move: a node can't go inside itself");
  var here = locate(surface, id);
  if (here && isSlotFrame(here.node) && here.parent && isSlotHost(here.parent) && (parentId || null) !== here.parent.id) throw new Error("[nexa] a component's slot stays in its component");
  var d = detach(surface, id);
  if (!d) return null;
  if (d.parentId === (parentId || null) && !d.orphan && index !== void 0 && index !== null && index > d.index) index--;
  insert(surface, parentId || null, index, d.node);
  return d.node;
}
function remove(surface, id) {
  var loc = locate(surface, id);
  var origin = loc && !loc.orphan ? absBox(surface, id) : { x: loc && loc.node.x || 0, y: loc && loc.node.y || 0 };
  var d = detach(surface, id);
  if (!d) return null;
  if (isContainer(d.node) && d.node.children && d.node.children.length) {
    surface.orphans = surface.orphans || [];
    var orphan = function(c, ox, oy) {
      c.x = (c.x || 0) + ox;
      c.y = (c.y || 0) + oy;
      surface.orphans.push(c);
    };
    if (isSlotHost(d.node)) {
      d.node.children.forEach(function(f) {
        var bw = borderOf(f);
        kids(f).forEach(function(c) {
          orphan(c, origin.x + (f.x || 0) + bw, origin.y + (f.y || 0) + bw);
        });
        f.children = [];
      });
    } else {
      d.node.children.forEach(function(c) {
        orphan(c, origin.x, origin.y);
      });
      d.node.children = [];
    }
  }
  return d.node;
}
function placeOrphan(surface, id, parentId, index) {
  var i = (surface.orphans || []).findIndex(function(n) {
    return n.id === id;
  });
  if (i === -1) return null;
  var node = surface.orphans.splice(i, 1)[0];
  insert(surface, parentId || null, index, node);
  return node;
}
function cloneWithNewIds(node, genId) {
  var copy = JSON.parse(JSON.stringify(node));
  (function renew(n) {
    n.id = genId();
    (n.children || []).forEach(renew);
  })(copy);
  return copy;
}
function contentOrigin(surface, id) {
  var b = absBox(surface, id);
  if (!b) return { x: 0, y: 0 };
  var bw = borderOf(find(surface, id));
  return { x: b.x + bw, y: b.y + bw };
}
function borderOf(node) {
  var st = node && node.type === "@frame" && node.style;
  var w = st && st.stroke ? Number(st.strokeWidth) : 0;
  return w > 0 ? w : 0;
}
function absBox(surface, id) {
  var loc = locate(surface, id);
  if (!loc) return null;
  var n = loc.node;
  var x = n.x || 0, y = n.y || 0;
  if (!onScreen(n)) {
    var chain = ancestors(surface, id).reverse();
    for (var i = 0; i < chain.length; i++) {
      var a = chain[i], b = borderOf(a);
      x += (a.x || 0) + b;
      y += (a.y || 0) + b;
      if (onScreen(a)) break;
    }
  }
  return { x, y, w: n.w || 0, h: n.h || 0 };
}
function onScreen(node) {
  return !!node && node.place === "screen" && !(node.type === "@frame" && node.inSlot) && !(node.overlay && node.overlay.kind);
}
function parentSize(surface, id) {
  var p = parentOf(surface, id);
  return p ? { w: p.w || 0, h: p.h || 0 } : { w: surface.width || 0, h: surface.height || 0 };
}
function childBounds(node) {
  var list = kids(node);
  if (!list.length) return null;
  var minX = Infinity, minY = Infinity, maxX = -Infinity, maxY = -Infinity;
  list.forEach(function(c) {
    minX = Math.min(minX, c.x || 0);
    minY = Math.min(minY, c.y || 0);
    maxX = Math.max(maxX, (c.x || 0) + (c.w || 0));
    maxY = Math.max(maxY, (c.y || 0) + (c.h || 0));
  });
  return { x: minX, y: minY, w: maxX - minX, h: maxY - minY };
}
function fitGroup(group) {
  if (!group || group.type !== "@group") return group;
  var b = childBounds(group);
  if (!b) return group;
  if (b.x !== 0 || b.y !== 0) {
    kids(group).forEach(function(c) {
      c.x = (c.x || 0) - b.x;
      c.y = (c.y || 0) - b.y;
    });
    group.x = (group.x || 0) + b.x;
    group.y = (group.y || 0) + b.y;
  }
  group.w = b.w;
  group.h = b.h;
  return group;
}
function refitGroupsUp(surface, id) {
  ancestors(surface, id).reverse().forEach(function(a) {
    if (a.type === "@group") fitGroup(a);
  });
}
function tidyContainer(surface, id) {
  var dropped = [];
  var loc = id ? locate(surface, id) : null;
  while (loc && !loc.orphan && loc.node.type === "@group" && !kids(loc.node).length) {
    var parentId = loc.parent ? loc.parent.id : null;
    loc.list.splice(loc.index, 1);
    dropped.push(loc.node.id);
    loc = parentId ? locate(surface, parentId) : null;
  }
  if (loc && !loc.orphan) {
    fitGroup(loc.node);
    refitGroupsUp(surface, loc.node.id);
  }
  return dropped;
}
function wrapIn(surface, ids, container) {
  return wrapInGroup(surface, ids, container);
}
function wrapInGroup(surface, ids, group) {
  var locs = ids.map(function(id) {
    return locate(surface, id);
  }).filter(Boolean);
  if (!locs.length) return null;
  var parent = locs[0].parent;
  if (locs.some(function(l) {
    return l.parent !== parent || l.orphan;
  })) throw new Error("[nexa] wrap: nodes must share one parent");
  if (parent && isSlotHost(parent)) throw new Error("[nexa] wrap: a component's slots stay in it");
  locs.sort(function(a, b2) {
    return a.index - b2.index;
  });
  var at = locs[locs.length - 1].index - (locs.length - 1);
  var list = listOf(surface, parent);
  locs.slice().reverse().forEach(function(l) {
    list.splice(l.index, 1);
  });
  group.type = group.type === "@frame" ? "@frame" : "@group";
  group.children = locs.map(function(l) {
    return l.node;
  });
  group.x = 0;
  group.y = 0;
  var b = childBounds(group);
  kids(group).forEach(function(c) {
    c.x = (c.x || 0) - b.x;
    c.y = (c.y || 0) - b.y;
  });
  group.x = b.x;
  group.y = b.y;
  group.w = b.w;
  group.h = b.h;
  list.splice(at, 0, group);
  return group;
}
function unwrap(surface, id) {
  var loc = locate(surface, id);
  if (!loc || !isContainer(loc.node) || isSlotHost(loc.node) || isSlotFrame(loc.node) && isSlotHost(loc.parent)) return [];
  var g = loc.node;
  var children = kids(g);
  children.forEach(function(c) {
    c.x = (c.x || 0) + (g.x || 0);
    c.y = (c.y || 0) + (g.y || 0);
  });
  loc.list.splice.apply(loc.list, [loc.index, 1].concat(children));
  return children;
}
var VIS_RANK = { show: 0, hide: 1, remove: 2 };
function effectiveVisibility(surface, id) {
  var chain = ancestors(surface, id).concat([find(surface, id)]);
  var eff = "show";
  chain.forEach(function(n) {
    var v = n && n.visibility || "show";
    if (VIS_RANK[v] > VIS_RANK[eff]) eff = v;
  });
  return eff;
}
function effectiveLocked(surface, id) {
  return ancestors(surface, id).concat([find(surface, id)]).some(function(n) {
    return n && n.locked;
  });
}
function findByName(surface, name) {
  var out = [];
  walk(surface, function(n) {
    if (isContainer(n) && n.name === name) out.push(n);
  });
  return out;
}

// src/model/theme.js
var PALETTES = {
  gray: ["#f4f4f4", "#e0e0e0", "#c6c6c6", "#a8a8a8", "#8d8d8d", "#6f6f6f", "#525252", "#393939", "#262626", "#161616", "#0b0b0b"],
  red: ["#fff1f1", "#ffd7d9", "#ffb3b8", "#ff8389", "#fa4d56", "#ea3640", "#da1e28", "#a2191f", "#750e13", "#520408", "#2d0709"],
  orange: ["#fff2e8", "#ffd9be", "#ffb784", "#ff9d57", "#ff832b", "#f57316", "#eb6200", "#ba4e00", "#8a3800", "#5e2900", "#3e1a00"],
  yellow: ["#fcf4d6", "#fdf0b5", "#fddc69", "#f7d138", "#f1c21b", "#e5b400", "#d2a106", "#b28600", "#8e6a00", "#684e00", "#302400"],
  green: ["#defbe6", "#a7f0ba", "#6fdc8c", "#42be65", "#24a148", "#1f9140", "#198038", "#0e6027", "#044317", "#022d0d", "#071908"],
  teal: ["#d9fbfb", "#9ef0f0", "#3ddbd9", "#08bdba", "#009d9a", "#008d8a", "#007d79", "#005d5d", "#004144", "#022b30", "#081a1c"],
  blue: ["#edf5ff", "#d0e2ff", "#a6c8ff", "#78a9ff", "#4589ff", "#2a76fe", "#0f62fe", "#0043ce", "#002d9c", "#001d6c", "#001141"],
  cyan: ["#e5f6ff", "#bae6ff", "#82cfff", "#33b1ff", "#1192e8", "#0a82d6", "#0072c3", "#00539a", "#003a6d", "#012749", "#061727"],
  purple: ["#f6f2ff", "#e8daff", "#d4bbff", "#be95ff", "#a56eff", "#9756fd", "#8a3ffc", "#6929c4", "#491d8b", "#31135e", "#1c0f30"],
  pink: ["#fff0f7", "#ffd6e8", "#ffafd2", "#ff7eb6", "#ee5396", "#df3d83", "#d02670", "#9f1853", "#740937", "#510224", "#2a0a18"]
};
var SHADES = ["50", "100", "200", "300", "400", "500", "600", "700", "800", "900", "950"];
function shadesOf(list) {
  var o = {};
  SHADES.forEach(function(s, i) {
    o[s] = list[i];
  });
  return o;
}
function sem(light, dark) {
  return { light, dark: dark === void 0 ? light : dark };
}
var DEFAULT_SEMANTIC = {
  "bg": sem("{colors.white}", "{colors.gray.900}"),
  "bg.subtle": sem("{colors.gray.50}", "{colors.gray.800}"),
  "bg.muted": sem("{colors.gray.100}", "{colors.gray.700}"),
  "bg.emphasized": sem("{colors.gray.200}", "{colors.gray.600}"),
  "bg.inverted": sem("{colors.gray.900}", "{colors.gray.50}"),
  "bg.panel": sem("{colors.white}", "{colors.gray.800}"),
  "bg.error": sem("{colors.red.50}", "{colors.red.950}"),
  "bg.warning": sem("{colors.yellow.50}", "{colors.yellow.950}"),
  "bg.success": sem("{colors.green.50}", "{colors.green.950}"),
  "bg.info": sem("{colors.blue.50}", "{colors.blue.950}"),
  "fg": sem("{colors.gray.900}", "{colors.gray.50}"),
  "fg.muted": sem("{colors.gray.600}", "{colors.gray.200}"),
  "fg.subtle": sem("{colors.gray.300}", "{colors.gray.500}"),
  "fg.inverted": sem("{colors.white}", "{colors.gray.900}"),
  "fg.error": sem("{colors.red.600}", "{colors.red.300}"),
  "fg.warning": sem("{colors.yellow.800}", "{colors.yellow.400}"),
  "fg.success": sem("{colors.green.600}", "{colors.green.300}"),
  "fg.info": sem("{colors.blue.700}", "{colors.blue.300}"),
  "border": sem("{colors.gray.200}", "{colors.gray.700}"),
  "border.muted": sem("{colors.gray.100}", "{colors.gray.800}"),
  "border.subtle": sem("{colors.gray.50}", "{colors.gray.800}"),
  "border.emphasized": sem("{colors.gray.400}", "{colors.gray.500}"),
  "border.inverted": sem("{colors.gray.900}", "{colors.gray.50}"),
  "border.error": sem("{colors.red.600}", "{colors.red.400}"),
  "border.warning": sem("{colors.yellow.400}", "{colors.yellow.400}"),
  "border.success": sem("{colors.green.400}", "{colors.green.400}"),
  "border.info": sem("{colors.blue.600}", "{colors.blue.400}")
};
var STACK = "'IBM Plex Sans', Inter, ui-sans-serif, system-ui, -apple-system, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif";
var DEFAULT_THEME = {
  defaultMode: "light",
  // light | dark | system (the viewer's OS setting)
  primary: "blue",
  // colors.primary.* = this palette's
  palettes: (function() {
    var o = {};
    Object.keys(PALETTES).forEach(function(k) {
      o[k] = shadesOf(PALETTES[k]);
    });
    return o;
  })(),
  semantic: DEFAULT_SEMANTIC,
  fonts: { heading: STACK, body: STACK, mono: "'IBM Plex Mono', ui-monospace, SFMono-Regular, Menlo, Consolas, 'Liberation Mono', monospace" },
  // px (numbers): font sizes, spacing, radii
  fontSizes: { "2xs": 10, xs: 12, sm: 14, md: 16, lg: 18, xl: 20, "2xl": 24, "3xl": 28, "4xl": 32, "5xl": 42, "6xl": 54, "7xl": 60 },
  fontWeights: { thin: 100, extralight: 200, light: 300, normal: 400, medium: 500, semibold: 600, bold: 700, extrabold: 800, black: 900 },
  lineHeights: { none: 1, shorter: 1.25, short: 1.375, moderate: 1.5, tall: 1.625, taller: 2 },
  letterSpacings: { tighter: "-0.02em", tight: "-0.01em", normal: "0", wide: "0.01em", wider: "0.027em", widest: "0.1em" },
  spacing: { "0": 0, "0.5": 2, "1": 4, "1.5": 6, "2": 8, "2.5": 10, "3": 12, "3.5": 14, "4": 16, "5": 20, "6": 24, "7": 28, "8": 32, "9": 36, "10": 40, "12": 48, "14": 56, "16": 64, "20": 80, "24": 96, "32": 128, "40": 160 },
  // sharp, a little softened: md = 4
  radii: { none: 0, "2xs": 1, xs: 2, sm: 2, md: 4, lg: 6, xl: 8, "2xl": 12, "3xl": 16, "4xl": 24, full: 9999 },
  shadows: {
    xs: "0 1px 2px rgba(0,0,0,0.1)",
    sm: "0 1px 3px rgba(0,0,0,0.15)",
    md: "0 2px 6px rgba(0,0,0,0.2)",
    lg: "0 4px 12px rgba(0,0,0,0.25)",
    xl: "0 8px 24px rgba(0,0,0,0.3)",
    "2xl": "0 16px 48px rgba(0,0,0,0.35)",
    inner: "inset 0 1px 2px rgba(0,0,0,0.1)"
  },
  // Carbon's motion: fast-01 … slow-02
  durations: { fastest: "70ms", faster: "110ms", fast: "150ms", moderate: "240ms", slow: "400ms", slower: "700ms", slowest: "900ms" },
  zIndex: { hide: -1, base: 0, docked: 10, dropdown: 1e3, sticky: 1100, banner: 1200, overlay: 1300, modal: 1400, popover: 1500, toast: 1700, tooltip: 1800 }
};
var TOKEN_CATEGORIES = ["colors", "fonts", "fontSizes", "fontWeights", "lineHeights", "letterSpacings", "spacing", "radii", "shadows", "durations", "zIndex"];
var PX = { fontSizes: true, spacing: true, radii: true };
var BASE_COLORS = { white: "#ffffff", black: "#000000", transparent: "transparent", current: "currentColor" };
var PALETTE_ROLES = ["solid", "contrast", "fg", "muted", "subtle", "emphasized", "focusRing", "border"];
function clone(v) {
  return v === void 0 || v === null || typeof v !== "object" ? v : JSON.parse(JSON.stringify(v));
}
function themeOf(app) {
  var own = app && app.theme || {};
  var t = clone(DEFAULT_THEME);
  Object.keys(own).forEach(function(k) {
    if (own[k] === void 0 || own[k] === null) return;
    t[k] = clone(own[k]);
  });
  if (!t.palettes || !Object.keys(t.palettes).length) t.palettes = clone(DEFAULT_THEME.palettes);
  if (!t.palettes[t.primary]) t.primary = t.palettes.blue ? "blue" : Object.keys(t.palettes)[0];
  return t;
}
function hexToHsl(hex) {
  var m = /^#?([0-9a-f]{6})$/i.exec(String(hex || "").trim());
  if (!m) return null;
  var n = parseInt(m[1], 16), r = (n >> 16 & 255) / 255, g = (n >> 8 & 255) / 255, b = (n & 255) / 255;
  var max = Math.max(r, g, b), min = Math.min(r, g, b), l = (max + min) / 2, h = 0, s = 0;
  if (max !== min) {
    var d = max - min;
    s = l > 0.5 ? d / (2 - max - min) : d / (max + min);
    h = max === r ? (g - b) / d + (g < b ? 6 : 0) : max === g ? (b - r) / d + 2 : (r - g) / d + 4;
    h /= 6;
  }
  return { h: h * 360, s: s * 100, l: l * 100 };
}
function hslToHex(h, s, l) {
  s /= 100;
  l /= 100;
  var k = function(n) {
    return (n + h / 30) % 12;
  };
  var a = s * Math.min(l, 1 - l);
  var f = function(n) {
    return l - a * Math.max(-1, Math.min(k(n) - 3, Math.min(9 - k(n), 1)));
  };
  return "#" + [f(0), f(8), f(4)].map(function(x) {
    var v = Math.round(x * 255).toString(16);
    return v.length < 2 ? "0" + v : v;
  }).join("");
}
var TOWARDS = [0.93, 0.83, 0.66, 0.46, 0.24, 0, 0.18, 0.36, 0.54, 0.7, 0.86];
function generatePalette(base) {
  var hsl = hexToHsl(base);
  if (!hsl) return null;
  var out = {};
  SHADES.forEach(function(s, i) {
    if (i === 5) {
      out[s] = String(base).toLowerCase();
      return;
    }
    var l = i < 5 ? hsl.l + (97 - hsl.l) * TOWARDS[i] : hsl.l - (hsl.l - 8) * TOWARDS[i];
    var sat = i < 5 ? Math.min(100, hsl.s * (0.8 + i * 0.04)) : hsl.s;
    out[s] = hslToHex(hsl.h, sat, l);
  });
  return out;
}
function paletteRole(name, role) {
  var p = "{colors." + name + ".";
  if (name === "gray") {
    return {
      solid: sem(p + "900}", "{colors.white}"),
      contrast: sem("{colors.white}", "{colors.black}"),
      fg: sem(p + "800}", p + "200}"),
      muted: sem(p + "200}", p + "800}"),
      subtle: sem(p + "100}", p + "900}"),
      emphasized: sem(p + "300}", p + "700}"),
      focusRing: sem(p + "800}", p + "200}"),
      border: sem(p + "200}", p + "800}")
    }[role];
  }
  return {
    solid: sem(p + "600}", p + "600}"),
    contrast: sem(name === "yellow" ? "{colors.black}" : "{colors.white}"),
    fg: sem(p + "700}", p + "300}"),
    muted: sem(p + "200}", p + "800}"),
    subtle: sem(p + "100}", p + "900}"),
    emphasized: sem(p + "300}", p + "700}"),
    focusRing: sem(p + "500}", p + "500}"),
    border: sem(p + "500}", p + "400}")
  }[role];
}
function listTokens(theme, category) {
  var t = theme || DEFAULT_THEME, out = [];
  function add(path, cat, light, dark, semantic) {
    if (!category || category === cat) out.push({ path, category: cat, light, dark: dark === void 0 ? light : dark, semantic: !!semantic });
  }
  Object.keys(BASE_COLORS).forEach(function(k) {
    add("colors." + k, "colors", BASE_COLORS[k]);
  });
  Object.keys(t.semantic || {}).forEach(function(k) {
    var v = t.semantic[k] || {};
    add("colors." + k, "colors", v.light, v.dark, true);
  });
  var palettes = t.palettes || {};
  var names = Object.keys(palettes).concat(palettes[t.primary] ? ["primary"] : []);
  names.forEach(function(name) {
    var real = name === "primary" ? t.primary : name;
    SHADES.forEach(function(s) {
      if (palettes[real] && palettes[real][s]) add("colors." + name + "." + s, "colors", name === "primary" ? "{colors." + real + "." + s + "}" : palettes[real][s]);
    });
    PALETTE_ROLES.forEach(function(role) {
      var r = paletteRole(real, role);
      add("colors." + name + "." + role, "colors", r.light, r.dark, true);
    });
  });
  TOKEN_CATEGORIES.forEach(function(cat) {
    if (cat === "colors") return;
    Object.keys(t[cat] || {}).forEach(function(k) {
      add(cat + "." + k, cat, t[cat][k]);
    });
  });
  return out;
}
var cache = { theme: null, index: null };
function indexOf(theme) {
  if (cache.theme === theme && cache.index) return cache.index;
  var ix = {};
  listTokens(theme).forEach(function(tk) {
    ix[tk.path] = tk;
  });
  cache.theme = theme;
  cache.index = ix;
  return ix;
}
var REF_RE = /\{([A-Za-z0-9_.\-]+)\}/g;
function resolveToken(theme, path, mode) {
  var ix = indexOf(theme || DEFAULT_THEME);
  var seen = 0;
  function value(p) {
    var tk = ix[p];
    if (!tk) return void 0;
    var v = mode === "dark" ? tk.dark : tk.light;
    return follow(v);
  }
  function follow(v) {
    if (typeof v !== "string" || v.indexOf("{") === -1 || ++seen > 20) return v;
    var whole = /^\{([A-Za-z0-9_.\-]+)\}$/.exec(v.trim());
    if (whole) return value(whole[1]);
    return v.replace(REF_RE, function(m, p) {
      var r = value(p);
      return r === void 0 ? m : String(r);
    });
  }
  return value(path);
}
function tokenVarName(path) {
  return "--nexa-" + String(path).replace(/\./g, "-").replace(/[^A-Za-z0-9_-]/g, "_");
}
function tokenVar(path) {
  return "var(" + tokenVarName(path) + ")";
}
function cssValue(cat, v) {
  return PX[cat] && typeof v === "number" ? v + "px" : String(v);
}
function themeCss(theme, root, dark) {
  var t = theme || DEFAULT_THEME;
  var light = [], darkRules = [];
  listTokens(t).forEach(function(tk) {
    var l = resolveToken(t, tk.path, "light"), d = resolveToken(t, tk.path, "dark");
    if (l === void 0) return;
    light.push(tokenVarName(tk.path) + ": " + cssValue(tk.category, l) + ";");
    if (d !== void 0 && String(d) !== String(l)) darkRules.push(tokenVarName(tk.path) + ": " + cssValue(tk.category, d) + ";");
  });
  return (root || ":root") + " { " + light.join(" ") + " }\n" + (dark || '[data-nexa-mode="dark"]') + " { " + darkRules.join(" ") + " }";
}
var TOKEN_RE = /\{token:([A-Za-z0-9_.\-]+)\}/g;
var WHOLE_TOKEN_RE = /^\{token:([A-Za-z0-9_.\-]+)\}$/;
function isTokenRef(v) {
  return typeof v === "string" && WHOLE_TOKEN_RE.test(v.trim());
}
function tokenPathOf(v) {
  var m = typeof v === "string" && WHOLE_TOKEN_RE.exec(v.trim());
  return m ? m[1] : null;
}
function mentionsToken(v) {
  return typeof v === "string" && v.indexOf("{token:") !== -1;
}
function resolveTokenValue(v, theme, mode) {
  if (!mentionsToken(v)) return v;
  var whole = WHOLE_TOKEN_RE.exec(v.trim());
  if (whole) {
    var r = resolveToken(theme, whole[1], mode);
    return r === void 0 ? v : r;
  }
  return v.replace(TOKEN_RE, function(m, p) {
    var r2 = resolveToken(theme, p, mode);
    return r2 === void 0 ? m : String(r2);
  });
}
function resolveTokenProps(props, theme, mode) {
  var out = null;
  Object.keys(props || {}).forEach(function(k) {
    if (!mentionsToken(props[k])) return;
    if (!out) out = Object.assign({}, props);
    out[k] = resolveTokenValue(props[k], theme, mode);
  });
  return out || props;
}
function tokenCss(v) {
  if (!mentionsToken(v)) return v;
  return v.replace(TOKEN_RE, function(m, p) {
    return tokenVar(p);
  });
}
var current = { theme: DEFAULT_THEME, mode: "light" };
function setTheme(theme, mode) {
  if (theme) current.theme = theme;
  if (mode) current.mode = mode === "dark" ? "dark" : "light";
  return current;
}
function currentTheme() {
  return current;
}

// src/model/layout.js
var LAYOUT_MODES = ["none", "horizontal", "vertical", "grid", "carousel"];
var CAROUSEL_DEFAULT = {
  direction: "horizontal",
  // "horizontal" | "vertical"
  perView: 1,
  transition: "slide",
  // "slide" | "fade"
  loop: false,
  autoplay: 0,
  // ms between slides, 0 = off
  pauseOnHover: true,
  arrows: true,
  dots: true,
  swipe: true,
  index: ""
  // a variable name: the current slide (0-based)
};
var DEFAULT_LAYOUT = {
  mode: "none",
  padding: { t: 0, r: 0, b: 0, l: 0 },
  gap: 0,
  rowGap: void 0,
  // unset: the same as gap
  alignX: "start",
  alignY: "start",
  wrap: false,
  columns: [{ size: 1, unit: "fr" }, { size: 1, unit: "fr" }],
  rows: [],
  sizeW: "fixed",
  sizeH: "fixed",
  carousel: null,
  items: null
};
var ITEMS_DEFAULT = { padX: 0, padY: 0, alignX: "center", alignY: "center" };
var TEMPLATE_LIVE_DEFAULT = { w: "fixed", h: "fixed", minW: "", maxW: "", minH: "", maxH: "", content: "constraints" };
var TEMPLATE_CONTENT_MODES = ["constraints", "scale", "stretch"];
function templateLiveOf(template) {
  var live = Object.assign({}, TEMPLATE_LIVE_DEFAULT, template && template.live || {});
  if (TEMPLATE_CONTENT_MODES.indexOf(live.content) === -1) live.content = "constraints";
  return live;
}
function templateContentOf(template, instance) {
  var own = instance && instance.content;
  return TEMPLATE_CONTENT_MODES.indexOf(own) !== -1 ? own : templateLiveOf(template).content;
}
function templateContentFit(template, bw, bh, instance) {
  var mode = templateContentOf(template, instance);
  if (mode === "constraints") return null;
  var tw = Number(template && template.width) || 1, th = Number(template && template.height) || 1;
  var sx = bw / tw, sy = bh / th;
  if (!(sx > 0) || !(sy > 0)) return { transform: "", left: 0, top: 0 };
  if (mode === "stretch") return { transform: "scale(" + sx + "," + sy + ")", left: 0, top: 0 };
  var s = Math.min(sx, sy);
  return { transform: "scale(" + s + ")", left: (bw - tw * s) / 2, top: (bh - th * s) / 2 };
}
function guessConstraints(node, pw, ph) {
  function axis(pos, size, total, a, b, both) {
    var near = pos, far = total - pos - size;
    if (size >= total * 0.35) return both;
    if (Math.abs(near - far) <= total * 0.06) return "center";
    return far < near ? b : a;
  }
  return {
    h: axis(num(node.x), num(node.w), pw, "left", "right", "leftRight"),
    v: axis(num(node.y), num(node.h), ph, "top", "bottom", "topBottom")
  };
}
var DEFAULT_STYLE = { fill: "", stroke: "", strokeWidth: 0, radius: 0, clip: false, scroll: "none", scrollbar: "auto" };
var SCROLL_AXES = { vertical: ["hidden", "auto"], horizontal: ["auto", "hidden"], both: ["auto", "auto"] };
function num(v, d) {
  var n = typeof v === "number" ? v : parseFloat(v);
  return isFinite(n) ? n : d || 0;
}
function pxCss(v) {
  return mentionsToken(v) ? tokenCss(v) : num(v) + "px";
}
function has(v) {
  return mentionsToken(v) || num(v) > 0;
}
function layoutOf(frame) {
  var l = frame && frame.layout || {};
  var out = {};
  Object.keys(DEFAULT_LAYOUT).forEach(function(k) {
    out[k] = l[k] !== void 0 ? l[k] : DEFAULT_LAYOUT[k];
  });
  var p = out.padding || {};
  out.padding = { t: num(p.t), r: num(p.r), b: num(p.b), l: num(p.l) };
  if (LAYOUT_MODES.indexOf(out.mode) === -1) out.mode = "none";
  if (!Array.isArray(out.columns)) out.columns = DEFAULT_LAYOUT.columns;
  if (!Array.isArray(out.rows)) out.rows = [];
  out.carousel = Object.assign({}, CAROUSEL_DEFAULT, l.carousel || {});
  out.items = Object.assign({}, ITEMS_DEFAULT, l.items || {});
  var pv = num(out.carousel.perView, 1);
  out.carousel.perView = pv > 0 ? pv : 1;
  return out;
}
var OVERLAY_KINDS = ["dialog", "drawer"];
var OVERLAY_DEFAULT = {
  kind: "dialog",
  alignX: "center",
  alignY: "center",
  margin: 16,
  side: "right",
  backdrop: "dim",
  backdropOpacity: 0.4,
  modal: true,
  closeOnBackdrop: true,
  closeOnEsc: true,
  autoClose: 0,
  draggable: false,
  dragWithin: "scope",
  animation: "auto",
  duration: 200,
  startOpen: false
};
function overlayOf(node) {
  if (!node || node.type !== "@frame" || !node.overlay || OVERLAY_KINDS.indexOf(node.overlay.kind) === -1) return null;
  var o = Object.assign({}, OVERLAY_DEFAULT, node.overlay);
  o.margin = Math.max(0, num(o.margin, 16));
  o.duration = Math.max(0, num(o.duration, 200));
  o.autoClose = Math.max(0, num(o.autoClose, 0));
  o.backdropOpacity = Math.min(1, Math.max(0, num(o.backdropOpacity, 0.4)));
  if (["left", "right", "top", "bottom"].indexOf(o.side) === -1) o.side = "right";
  if (o.animation === "auto") o.animation = o.kind === "drawer" ? "slide" : "scale";
  return o;
}
function overlayBox(node, pw, ph) {
  var o = overlayOf(node);
  var w = num(node.w), h = num(node.h);
  if (!o) return { x: num(node.x), y: num(node.y), w, h };
  if (o.kind === "drawer") {
    if (o.side === "left") return { x: 0, y: 0, w: Math.min(w, pw), h: ph };
    if (o.side === "right") return { x: Math.max(0, pw - w), y: 0, w: Math.min(w, pw), h: ph };
    if (o.side === "top") return { x: 0, y: 0, w: pw, h: Math.min(h, ph) };
    return { x: 0, y: Math.max(0, ph - h), w: pw, h: Math.min(h, ph) };
  }
  var m = o.margin;
  var cw = Math.min(w, Math.max(0, pw - 2 * m)), ch = Math.min(h, Math.max(0, ph - 2 * m));
  return { x: m + (pw - 2 * m - cw) * alignFraction(o.alignX), y: m + (ph - 2 * m - ch) * alignFraction(o.alignY), w: cw, h: ch };
}
var ZOOM_DEFAULT = { enabled: false, min: 0.25, max: 4, wheel: "ctrl", controls: true, start: "fit", dblclick: true };
function zoomOf(frame) {
  if (!frame || frame.type !== "@frame" || !frame.zoom || !frame.zoom.enabled) return null;
  if (layoutOf(frame).mode === "carousel") return null;
  var z = Object.assign({}, ZOOM_DEFAULT, frame.zoom);
  z.min = Math.max(0.05, num(z.min, 0.25));
  z.max = Math.max(z.min, num(z.max, 4));
  return z;
}
function carouselOf(frame) {
  return frame && frame.type === "@frame" && layoutOf(frame).mode === "carousel" ? layoutOf(frame).carousel : null;
}
function alignFraction(a) {
  return a === "center" ? 0.5 : a === "end" ? 1 : 0;
}
function flowAxis(frame) {
  var l = layoutOf(frame);
  if (l.mode === "carousel") return l.carousel.direction === "vertical" ? "vertical" : "horizontal";
  return l.mode;
}
function styleOf(frame) {
  var s = frame && frame.style || {};
  var out = {};
  Object.keys(DEFAULT_STYLE).forEach(function(k) {
    out[k] = s[k] !== void 0 ? s[k] : DEFAULT_STYLE[k];
  });
  return out;
}
function hasAutoLayout(node) {
  return !!node && node.type === "@frame" && layoutOf(node).mode !== "none";
}
function inSlot(node) {
  return !!(node && node.type === "@frame" && typeof node.inSlot === "string" && node.inSlot !== "");
}
function isInFlow(child, parent) {
  return hasAutoLayout(parent) && !(child && child.layoutChild && child.layoutChild.absolute) && !overlayOf(child) && !placedOut(child);
}
var PLACES = ["flow", "free", "screen", "dock"];
function placedOut(node) {
  return !!node && (node.place === "screen" || node.place === "dock") && !inSlot(node);
}
function placeOf(node, parent) {
  if (!node) return "free";
  if (placedOut(node) && !overlayOf(node)) return node.place;
  if (hasAutoLayout(parent) && !(node.layoutChild && node.layoutChild.absolute) && !overlayOf(node) && !inSlot(node)) return "flow";
  return "free";
}
function dockOf(node) {
  var d = node && node.dock || {};
  var v = function(s, def) {
    return s === "start" || s === "center" || s === "end" ? s : def;
  };
  return { x: v(d.x, "start"), y: v(d.y, "start"), stretch: !!d.stretch };
}
function sides(v) {
  if (v === void 0 || v === null || v === "") return { t: 0, r: 0, b: 0, l: 0 };
  if (typeof v === "number") return { t: v, r: v, b: v, l: v };
  return { t: num(v.t), r: num(v.r), b: num(v.b), l: num(v.l) };
}
function marginOf(node) {
  return sides(node && node.margin);
}
function paddingOf(node) {
  return sides(node && node.padding);
}
function takesPadding(node) {
  return !!node && ["@frame", "@group", "@template"].indexOf(node.type) === -1;
}
function zOf(node) {
  var z = Number(node && node.z);
  return isFinite(z) ? Math.round(z) : 0;
}
function pxSides(s) {
  return s.t + "px " + s.r + "px " + s.b + "px " + s.l + "px";
}
function hasSides(s) {
  return !!(s.t || s.r || s.b || s.l);
}
function dockCss(node, css) {
  var d = dockOf(node), m = marginOf(node);
  var w = num(node.w), h = num(node.h);
  css.position = "absolute";
  css.margin = "0px";
  css.left = css.right = css.top = css.bottom = "";
  var stretchX = d.stretch && d.x === "center" && d.y !== "center";
  var stretchY = d.stretch && d.y === "center" && d.x !== "center";
  if (stretchX) {
    css.left = m.l + "px";
    css.right = m.r + "px";
    css.width = "auto";
  } else if (d.x === "start") css.left = m.l + "px";
  else if (d.x === "end") {
    css.left = "auto";
    css.right = m.r + "px";
  } else css.left = "calc(50% - " + w / 2 + "px + " + (m.l - m.r) / 2 + "px)";
  if (stretchY) {
    css.top = m.t + "px";
    css.bottom = m.b + "px";
    css.height = "auto";
  } else if (d.y === "start") css.top = m.t + "px";
  else if (d.y === "end") {
    css.top = "auto";
    css.bottom = m.b + "px";
  } else css.top = "calc(50% - " + h / 2 + "px + " + (m.t - m.b) / 2 + "px)";
  return css;
}
function childSizing(child, axis) {
  var lc = child && child.layoutChild || {};
  var v = lc[axis];
  if (v === "fill") return "fill";
  if (v === "hug" && hasAutoLayout(child)) return "hug";
  return "fixed";
}
function frameHugs(frame, axis) {
  if (!hasAutoLayout(frame) || inSlot(frame)) return false;
  var l = layoutOf(frame);
  return (axis === "w" ? l.sizeW : l.sizeH) === "hug";
}
var FLEX_ALIGN = { start: "flex-start", center: "center", end: "flex-end" };
function track(t) {
  if (!t) return "1fr";
  if (t.unit === "auto") return "auto";
  var size = num(t.size, 1);
  return t.unit === "px" ? size + "px" : size + "fr";
}
function tracksCss(list) {
  return (list || []).map(track).join(" ");
}
function frameCss(frame, opts) {
  var l = layoutOf(frame);
  var s = styleOf(frame);
  var css = {
    background: tokenCss(s.fill) || "",
    border: has(s.strokeWidth) && s.stroke ? pxCss(s.strokeWidth) + " solid " + tokenCss(s.stroke) : "",
    "border-radius": has(s.radius) ? pxCss(s.radius) : "",
    overflow: s.clip ? "hidden" : "",
    "overflow-x": "",
    "overflow-y": "",
    "box-sizing": "border-box"
  };
  var axes = opts && opts.scroll && SCROLL_AXES[s.scroll];
  if (axes) {
    css.overflow = "";
    css["overflow-x"] = axes[0];
    css["overflow-y"] = axes[1];
  }
  css["scrollbar-width"] = opts && opts.scroll && s.scrollbar === "hidden" ? "none" : "";
  if (l.mode === "none") {
    css.display = "";
    css.padding = "";
    return css;
  }
  css.padding = l.padding.t + "px " + l.padding.r + "px " + l.padding.b + "px " + l.padding.l + "px";
  if (l.mode === "carousel") return Object.assign(css, carouselTrackCss(frame, opts && opts.scroll));
  if (l.mode === "grid") {
    css.display = "grid";
    css["grid-template-columns"] = tracksCss(l.columns) || "1fr";
    css["grid-template-rows"] = tracksCss(l.rows);
    css["grid-auto-rows"] = "auto";
    css["column-gap"] = pxCss(l.gap);
    css["row-gap"] = pxCss(l.rowGap !== void 0 && l.rowGap !== "" ? l.rowGap : l.gap);
    css["justify-items"] = l.alignX;
    css["align-items"] = l.alignY;
    css["align-content"] = l.alignY;
    css["justify-content"] = l.alignX;
  } else {
    var horizontal = l.mode === "horizontal";
    var main = horizontal ? l.alignX : l.alignY;
    var cross = horizontal ? l.alignY : l.alignX;
    css.display = "flex";
    css["flex-direction"] = horizontal ? "row" : "column";
    css["flex-wrap"] = horizontal && l.wrap ? "wrap" : "nowrap";
    css["justify-content"] = l.gap === "auto" ? "space-between" : FLEX_ALIGN[main] || "flex-start";
    css["align-items"] = FLEX_ALIGN[cross] || "flex-start";
    css["align-content"] = FLEX_ALIGN[horizontal ? l.alignY : l.alignX] || "flex-start";
    css[horizontal ? "column-gap" : "row-gap"] = l.gap === "auto" ? "0px" : pxCss(l.gap);
    css[horizontal ? "row-gap" : "column-gap"] = horizontal && l.wrap ? pxCss(l.rowGap !== void 0 && l.rowGap !== "" ? l.rowGap : l.gap) : "0px";
  }
  return css;
}
function carouselTrackCss(frame, live) {
  var l = layoutOf(frame), c = l.carousel;
  var horizontal = c.direction !== "vertical";
  var gap = l.gap === "auto" ? 0 : num(l.gap);
  var css = {
    "flex-wrap": "nowrap",
    "justify-content": "flex-start",
    "align-items": "stretch",
    "align-content": "",
    "column-gap": "0px",
    "row-gap": "0px",
    "grid-template-columns": "",
    "grid-template-rows": "",
    "scroll-snap-type": "",
    "overscroll-behavior": "",
    "scrollbar-width": ""
  };
  if (c.transition === "fade") {
    css.display = "grid";
    css["grid-template-columns"] = "100%";
    css["grid-template-rows"] = "100%";
    css.overflow = "hidden";
    css["overflow-x"] = "";
    css["overflow-y"] = "";
    return css;
  }
  css.display = "flex";
  css["flex-direction"] = horizontal ? "row" : "column";
  css[horizontal ? "column-gap" : "row-gap"] = gap + "px";
  if (live) {
    css.overflow = "";
    css["overflow-x"] = horizontal ? "auto" : "hidden";
    css["overflow-y"] = horizontal ? "hidden" : "auto";
    css["scroll-snap-type"] = (horizontal ? "x" : "y") + " mandatory";
    css["overscroll-behavior"] = "contain";
    css["scrollbar-width"] = "none";
  } else {
    css.overflow = "hidden";
    css["overflow-x"] = "";
    css["overflow-y"] = "";
  }
  return css;
}
function carouselSlideSize(frame) {
  var l = layoutOf(frame), n = l.carousel.perView;
  var gap = l.gap === "auto" ? 0 : num(l.gap);
  return gap && n !== 1 ? "calc((100% - " + gap * (n - 1) + "px) / " + n + ")" : 100 / n + "%";
}
var H_CONSTRAINTS = ["left", "right", "leftRight", "center", "scale"];
var V_CONSTRAINTS = ["top", "bottom", "topBottom", "center", "scale"];
function constraintsOf(node) {
  var c = node && node.constraints || {};
  return { h: H_CONSTRAINTS.indexOf(c.h) === -1 ? "leftRight" : c.h, v: V_CONSTRAINTS.indexOf(c.v) === -1 ? "topBottom" : c.v };
}
function hasConstraints(node, parent) {
  if (node && placeOf(node, parent) === "dock") return false;
  if (parent && parent.zoom && parent.zoom.enabled) return false;
  return !inSlot(node) && (!parent || parent.type === "@frame") && !isInFlow(node, parent) && !overlayOf(node);
}
function innerSize(frame) {
  var s = styleOf(frame);
  var bw = num(s.strokeWidth) > 0 && s.stroke ? num(s.strokeWidth) : 0;
  var w = num(frame && (frame.w != null ? frame.w : frame.width), 0);
  var h = num(frame && (frame.h != null ? frame.h : frame.height), 0);
  return { w: w ? w - 2 * bw : 0, h: h ? h - 2 * bw : 0 };
}
function axisCss(mode, pos, size, parentSize2, startProp, endProp, sizeProp) {
  var css = {};
  var end = parentSize2 - pos - size;
  css[startProp] = pos + "px";
  css[endProp] = "";
  css[sizeProp] = size + "px";
  if (mode === "right" || mode === "bottom") {
    css[startProp] = "auto";
    css[endProp] = Math.max(0, end) + "px";
  } else if (mode === "leftRight" || mode === "topBottom") {
    css[endProp] = Math.max(0, end) + "px";
    css[sizeProp] = "auto";
  } else if (mode === "center") css[startProp] = "calc(50% + " + (pos - parentSize2 / 2) + "px)";
  else if (mode === "scale" && parentSize2 > 0) {
    css[startProp] = pos / parentSize2 * 100 + "%";
    css[sizeProp] = size / parentSize2 * 100 + "%";
  }
  return css;
}
function constraintCss(node, parentSize2, explicitConstraints) {
  var c = explicitConstraints || constraintsOf(node);
  var h = axisCss(c.h, num(node.x), num(node.w), parentSize2.w, "left", "right", "width");
  var v = axisCss(c.v, num(node.y), num(node.h), parentSize2.h, "top", "bottom", "height");
  return Object.assign(h, v);
}
function axisResize(mode, pos, size, oldP, newP) {
  var d = newP - oldP;
  if (mode === "right" || mode === "bottom") return [pos + d, size];
  if (mode === "leftRight" || mode === "topBottom") return [pos, Math.max(1, size + d)];
  if (mode === "center") return [pos + d / 2, size];
  if (mode === "scale" && oldP > 0) return [pos * newP / oldP, Math.max(1, size * newP / oldP)];
  return [pos, size];
}
function resizeWithConstraints(box, constraints, oldP, newP) {
  var c = constraints || { h: "left", v: "top" };
  var h = axisResize(c.h, box.x, box.w, oldP.w, newP.w);
  var v = axisResize(c.v, box.y, box.h, oldP.h, newP.h);
  return { x: Math.round(h[0]), y: Math.round(v[0]), w: Math.round(h[1]), h: Math.round(v[1]) };
}
function inferNodeConstraints(node, parent, ps) {
  if (node && node.constraints && (node.constraints.h || node.constraints.v)) {
    return constraintsOf(node);
  }
  if (!ps || ps.w <= 0 || ps.h <= 0) return constraintsOf(node);
  if (parent && parent.zoom && parent.zoom.enabled) return constraintsOf(node);
  var pStyle = parent && styleOf(parent) || {};
  var pScroll = pStyle.scroll || "none";
  var nearX = num(node.x), farX = ps.w - nearX - num(node.w);
  var nearY = num(node.y), farY = ps.h - nearY - num(node.h);
  var h = pScroll !== "horizontal" && pScroll !== "both" && farX >= 0 && farX < nearX ? "right" : "left";
  var v = pScroll !== "vertical" && pScroll !== "both" && farY >= 0 && farY < nearY ? "bottom" : "top";
  return { h, v };
}
function boxCss(node, parent, opts) {
  if (inSlot(node)) {
    return {
      position: "absolute",
      left: "0",
      top: "0",
      width: "100%",
      height: "100%",
      right: "",
      bottom: "",
      flex: "",
      "align-self": "",
      "justify-self": "",
      "grid-column": "",
      "grid-row": "",
      "min-width": "",
      "max-width": "",
      "min-height": "",
      "max-height": "",
      "scroll-snap-align": "",
      "z-index": ""
    };
  }
  var css = {
    position: "absolute",
    left: num(node.x) + "px",
    top: num(node.y) + "px",
    width: num(node.w) + "px",
    height: num(node.h) + "px",
    right: "",
    bottom: "",
    flex: "",
    "align-self": "",
    "justify-self": "",
    "grid-column": "",
    "grid-row": "",
    "min-width": node.minW ? num(node.minW) + "px" : "",
    "max-width": node.maxW ? num(node.maxW) + "px" : "",
    "min-height": node.minH ? num(node.minH) + "px" : "",
    "max-height": node.maxH ? num(node.maxH) + "px" : "",
    "scroll-snap-align": "",
    "z-index": ""
  };
  if (opts && opts.constraints && hasConstraints(node, parent)) {
    var ps = parent ? innerSize(parent) : opts.parentSize;
    var c = inferNodeConstraints(node, parent, ps);
    if (ps && (c.h !== "left" || c.v !== "top")) Object.assign(css, constraintCss(node, ps, c));
  }
  if (frameHugs(node, "w")) css.width = "max-content";
  if (frameHugs(node, "h")) css.height = "max-content";
  var mg = marginOf(node), pd = paddingOf(node), place = placeOf(node, parent);
  css.margin = place === "flow" && hasSides(mg) ? pxSides(mg) : "";
  if (takesPadding(node)) css.padding = hasSides(pd) ? pxSides(pd) : "";
  if (zOf(node)) css["z-index"] = String(zOf(node));
  if (place === "dock") return dockCss(node, css);
  if (!isInFlow(node, parent)) return css;
  var mode = layoutOf(parent).mode;
  var sw = childSizing(node, "w"), sh = childSizing(node, "h");
  css.position = "relative";
  css.left = "auto";
  css.top = "auto";
  css.right = "";
  css.bottom = "";
  if (node.scrollBehavior === "sticky") {
    css.position = "sticky";
    css[flowAxis(parent) === "horizontal" ? "left" : "top"] = "0px";
    css["z-index"] = zOf(node) ? String(zOf(node)) : "2";
  }
  if (mode === "carousel") {
    var c = layoutOf(parent).carousel, alongX = c.direction !== "vertical";
    css.flex = "0 0 auto";
    if (c.transition === "fade") {
      css["grid-column"] = "1";
      css["grid-row"] = "1";
      css.width = "100%";
      css.height = "100%";
      return css;
    }
    css[alongX ? "width" : "height"] = carouselSlideSize(parent);
    css[alongX ? "height" : "width"] = "auto";
    css["align-self"] = "stretch";
    css[alongX ? "min-width" : "min-height"] = "0px";
    css["scroll-snap-align"] = "start";
    return css;
  }
  if (mode === "grid") {
    var lc = node.layoutChild || {};
    if (lc.col) css["grid-column"] = num(lc.col, 1) + (lc.colSpan > 1 ? " / span " + num(lc.colSpan, 1) : "");
    else if (lc.colSpan > 1) css["grid-column"] = "span " + num(lc.colSpan, 1);
    if (lc.row) css["grid-row"] = num(lc.row, 1) + (lc.rowSpan > 1 ? " / span " + num(lc.rowSpan, 1) : "");
    else if (lc.rowSpan > 1) css["grid-row"] = "span " + num(lc.rowSpan, 1);
    if (sw === "fill") {
      css.width = "auto";
      css["justify-self"] = "stretch";
    } else if (sw === "hug") css.width = "max-content";
    if (sh === "fill") {
      css.height = "auto";
      css["align-self"] = "stretch";
    } else if (sh === "hug") css.height = "max-content";
    return css;
  }
  var horizontal = mode === "horizontal";
  var mainSizing = horizontal ? sw : sh, crossSizing = horizontal ? sh : sw;
  var mainProp = horizontal ? "width" : "height", crossProp = horizontal ? "height" : "width";
  if (mainSizing === "fill") {
    css.flex = "1 1 0px";
    css[mainProp] = "auto";
    css[horizontal ? "min-width" : "min-height"] = css[horizontal ? "min-width" : "min-height"] || "0px";
  } else {
    css.flex = "0 0 auto";
    if (mainSizing === "hug") css[mainProp] = "max-content";
  }
  if (crossSizing === "fill") {
    css["align-self"] = "stretch";
    css[crossProp] = "auto";
  } else if (crossSizing === "hug") css[crossProp] = "max-content";
  return css;
}
function canRotate(node, parent) {
  return !isInFlow(node, parent) && !inSlot(node);
}
function makeFrame(mode, w, h) {
  var frame = { type: "@frame", w: w || 240, h: h || 160, children: [], constraints: { h: "leftRight", v: "topBottom" }, style: { fill: "#ffffff", stroke: "#d0d0d0", strokeWidth: 1, radius: 4, clip: false } };
  if (mode === "carousel") {
    frame.layout = { mode: "carousel", padding: { t: 0, r: 0, b: 0, l: 0 }, gap: 0, carousel: Object.assign({}, CAROUSEL_DEFAULT) };
    frame.style.clip = true;
    frame.style.stroke = "";
    frame.style.strokeWidth = 0;
  } else if (mode && mode !== "none") {
    frame.layout = { mode, padding: { t: 8, r: 8, b: 8, l: 8 }, gap: 8 };
    if (mode === "grid") frame.layout.columns = [{ size: 1, unit: "fr" }, { size: 1, unit: "fr" }];
  }
  return frame;
}

// src/model/types.js
var TYPES = [];
function setTypes(list) {
  TYPES = Array.isArray(list) ? list : [];
}
function getTypes() {
  return TYPES;
}
function findType(ref) {
  var id = typeof ref === "string" && ref.indexOf("type:") === 0 ? ref.slice(5) : ref;
  return TYPES.filter(function(t) {
    return t.id === id || t.name === id;
  })[0] || null;
}
function isTypeRef(dataType) {
  return typeof dataType === "string" && dataType.indexOf("type:") === 0;
}
function BindingRef(text, access) {
  this.__nexaBinding = text;
  this.access = access || "read";
}
BindingRef.prototype.toString = function() {
  return this.__nexaBinding;
};
BindingRef.prototype.toJSON = function() {
  return this.__nexaBinding;
};
function isBindingRef(v) {
  return !!v && typeof v === "object" && typeof v.__nexaBinding === "string";
}
function clone2(v) {
  return v !== null && typeof v === "object" ? JSON.parse(JSON.stringify(v)) : v;
}
function fillParams(text, params) {
  return String(text).replace(/\{([A-Za-z_$][\w$]*)\}/g, function(whole, name) {
    return Object.prototype.hasOwnProperty.call(params, name) && params[name] !== void 0 && params[name] !== null ? String(params[name]) : whole;
  });
}
function buildInstance(type, instName, params, overrides, depth, parentName) {
  depth = depth || 0;
  if (!type || depth > 8) return null;
  var p = {};
  (type.params || []).forEach(function(x) {
    if (x && x.name) p[x.name] = x.defaultValue;
  });
  Object.keys(params || {}).forEach(function(k) {
    p[k] = params[k];
  });
  p.InstanceName = instName;
  if (parentName) p.ParentInstanceName = parentName;
  overrides = overrides || {};
  var out = {};
  Object.defineProperty(out, "__type", { value: type.id, enumerable: false });
  (type.members || []).forEach(function(m) {
    if (!m || !m.name) return;
    var ov = Object.prototype.hasOwnProperty.call(overrides, m.id) ? overrides[m.id] : Object.prototype.hasOwnProperty.call(overrides, m.name) ? overrides[m.name] : void 0;
    if (isTypeRef(m.dataType)) {
      var sub = findType(m.dataType);
      out[m.name] = sub ? buildInstance(sub, m.name, Object.assign({}, p, ov && typeof ov === "object" ? ov : {}), {}, depth + 1, instName) : null;
    } else if (m.source) {
      out[m.name] = new BindingRef(fillParams(m.source, p), m.access);
    } else {
      out[m.name] = clone2(ov !== void 0 ? ov : m.defaultValue);
    }
  });
  return out;
}
function variableValue(v) {
  if (v && isTypeRef(v.type)) {
    var t = findType(v.type);
    return t ? buildInstance(t, v.name, v.params, v.overrides) : null;
  }
  return clone2(v ? v.defaultValue : void 0);
}
function memberAt(instance, path) {
  var cur = instance, member = null;
  for (var i = 0; i < path.length; i++) {
    if (!cur || typeof cur !== "object" || !cur.__type) return null;
    var t = findType(cur.__type);
    member = t && (t.members || []).filter(function(m) {
      return m.name === path[i];
    })[0];
    if (!member) return null;
    cur = cur[path[i]];
  }
  return member;
}
function memberPaths(type, prefix, depth) {
  depth = depth || 0;
  var out = [];
  if (!type || depth > 4) return out;
  (type.members || []).forEach(function(m) {
    if (!m || !m.name) return;
    var path = prefix ? prefix + "." + m.name : m.name;
    out.push({ path, member: m });
    if (isTypeRef(m.dataType)) out = out.concat(memberPaths(findType(m.dataType), path, depth + 1));
  });
  return out;
}

// src/model/scope.js
var NAME_RE = /^[A-Za-z_$][\w$]*$/;
function makeScope(parent, variables) {
  var scope = Object.create(parent || null);
  (variables || []).forEach(function(v) {
    if (v && typeof v.name === "string" && NAME_RE.test(v.name)) scope[v.name] = variableValue(v);
  });
  return scope;
}
function clone3(v) {
  return v !== null && typeof v === "object" ? JSON.parse(JSON.stringify(v)) : v;
}
function hasVariables(node) {
  return !!(node && Array.isArray(node.variables) && node.variables.length);
}
function surfaceScope(surface, isTemplate, parent) {
  var scope = makeScope(parent || null, surface && surface.variables);
  if (isTemplate) {
    (surface.params || []).forEach(function(p) {
      if (p && NAME_RE.test(p.name || "")) scope[p.name] = clone3(p.defaultValue);
    });
  }
  return scope;
}
function visibleVariables(surface, ancestors2, isTemplate, self, app) {
  var seen = {}, out = [];
  function add(list, owner, valueKey) {
    (list || []).forEach(function(v) {
      if (!v || !NAME_RE.test(v.name || "") || seen[v.name]) return;
      seen[v.name] = true;
      var t = isTypeRef(v.type) ? findType(v.type) : null;
      out.push({ name: v.name, type: t ? t.name : v.type || "string", value: t ? "(" + t.name + ")" : v[valueKey], owner, typeId: t ? t.id : void 0 });
      if (t) memberPaths(t).forEach(function(mp) {
        out.push({ name: v.name + "." + mp.path, type: mp.member.dataType || "string", value: mp.member.source ? "(" + (mp.member.access === "readwrite" ? "read / write" : "read") + " tag)" : mp.member.defaultValue, owner, member: true });
      });
    });
  }
  var chain = (ancestors2 || []).slice();
  if (self && hasVariables(self)) chain.push(self);
  for (var i = chain.length - 1; i >= 0; i--) {
    add(chain[i].variables, { id: chain[i].id, name: chain[i].name || chain[i].type, kind: "container" }, "defaultValue");
  }
  if (isTemplate) add(surface.params, { id: surface.id, name: surface.name || "template", kind: "template" }, "defaultValue");
  add(surface.variables, { id: surface.id, name: isTemplate ? surface.name || "template" : "screen", kind: isTemplate ? "template" : "screen" }, "defaultValue");
  if (app) add(app.variables, { id: "@app", name: "App", kind: "app" }, "defaultValue");
  return out;
}
function allDeclarations(surface, walk2, app) {
  var out = [];
  if (app) (app.variables || []).forEach(function(v) {
    out.push({ scopeId: "@app", scopeName: "App", variable: v });
  });
  (surface.params || []).forEach(function(p) {
    if (p && p.name) out.push({ scopeId: "", scopeName: "Template", variable: { id: p.id, name: p.name, type: p.type, defaultValue: p.defaultValue }, param: true });
  });
  (surface.variables || []).forEach(function(v) {
    out.push({ scopeId: "", scopeName: surface.params ? "Template" : "Screen", variable: v });
  });
  walk2(surface, function(node) {
    if (hasVariables(node)) node.variables.forEach(function(v) {
      out.push({ scopeId: node.id, scopeName: node.name || node.type, variable: v });
    });
  });
  return out;
}

// src/model/breakpoints.js
var DEFAULT_BREAKPOINTS = [
  { id: "xs", name: "xs", min: 0, preview: 390, device: "Phone" },
  { id: "sm", name: "sm", min: 640, preview: 640, device: "Large phone" },
  { id: "md", name: "md", min: 768, preview: 820, device: "Tablet" },
  { id: "lg", name: "lg", min: 1024, preview: 1024, device: "Tablet landscape / small laptop" },
  { id: "xl", name: "xl", min: 1280, preview: 1366, device: "Laptop" },
  { id: "2xl", name: "2xl", min: 1536, preview: 1600, device: "Desktop" },
  { id: "3xl", name: "3xl", min: 1920, preview: 1920, device: "Full HD and up" }
];
var DEVICE_PRESETS = [
  { name: "iPhone SE", w: 375, h: 667 },
  { name: "iPhone 15", w: 393, h: 852 },
  { name: "Android phone", w: 412, h: 915 },
  { name: "Phone landscape", w: 740, h: 360 },
  { name: 'HMI 7" (800 \xD7 480)', w: 800, h: 480 },
  { name: "iPad mini", w: 768, h: 1024 },
  { name: "iPad Air", w: 820, h: 1180 },
  { name: 'HMI 10" (1024 \xD7 600)', w: 1024, h: 600 },
  { name: "iPad Pro landscape", w: 1366, h: 1024 },
  { name: 'HMI 15" (1280 \xD7 800)', w: 1280, h: 800 },
  { name: "Laptop (1366 \xD7 768)", w: 1366, h: 768 },
  { name: "Laptop (1440 \xD7 900)", w: 1440, h: 900 },
  { name: "Desktop (1600 \xD7 900)", w: 1600, h: 900 },
  { name: "Full HD (1920 \xD7 1080)", w: 1920, h: 1080 },
  { name: "QHD (2560 \xD7 1440)", w: 2560, h: 1440 },
  { name: "4K (3840 \xD7 2160)", w: 3840, h: 2160 }
];
var LEGACY = { md: "tablet", sm: "phone" };
var OVERRIDABLE = [
  "x",
  "y",
  "w",
  "h",
  "visibility",
  "layout",
  "layoutChild",
  "style",
  "constraints",
  "props",
  "minW",
  "maxW",
  "minH",
  "maxH",
  "scrollBehavior",
  "overlay",
  "z",
  "margin",
  "padding",
  "dock"
];
var MERGED = { layout: true, layoutChild: true, style: true, constraints: true, props: true, overlay: true, dock: true };
function clone4(v) {
  return v === void 0 || v === null || typeof v !== "object" ? v : JSON.parse(JSON.stringify(v));
}
function isPlain(v) {
  return v !== null && typeof v === "object" && !Array.isArray(v);
}
function merge(into, patch) {
  var out = isPlain(into) ? clone4(into) : {};
  Object.keys(patch || {}).forEach(function(k) {
    out[k] = isPlain(patch[k]) && isPlain(out[k]) ? merge(out[k], patch[k]) : clone4(patch[k]);
  });
  return out;
}
function breakpointsOf(app) {
  var src = app && Array.isArray(app.breakpoints) && app.breakpoints.length ? app.breakpoints : DEFAULT_BREAKPOINTS;
  var seen = {};
  var list = src.filter(function(b) {
    if (!b || !b.id || seen[b.id] || !isFinite(Number(b.min))) return false;
    seen[b.id] = true;
    return true;
  }).map(function(b) {
    return Object.assign({}, b, { min: Math.max(0, Number(b.min)), name: b.name || b.id });
  }).sort(function(a, b) {
    return a.min - b.min;
  });
  if (!list.length) return breakpointsOf(null);
  list[0].min = 0;
  return list;
}
function bandOf(app, width) {
  var list = breakpointsOf(app), id = list[0].id;
  list.forEach(function(b) {
    if (Number(width) >= b.min) id = b.id;
  });
  return id;
}
function designBreakpoint(app, surface) {
  return bandOf(app, surface && surface.width ? surface.width : 1920);
}
function activeBreakpoint(app, surface, width) {
  return bandOf(app, width);
}
function chainFor(app, surface, id) {
  var list = breakpointsOf(app).map(function(b) {
    return b.id;
  });
  var d = list.indexOf(designBreakpoint(app, surface)), t = list.indexOf(id);
  if (t === -1 || d === -1 || t === d) return [];
  var out = [];
  if (t < d) for (var i = d - 1; i >= t; i--) out.push(list[i]);
  else for (var j = d + 1; j <= t; j++) out.push(list[j]);
  return out;
}
function rangeOf(app, id) {
  var list = breakpointsOf(app);
  for (var i = 0; i < list.length; i++) {
    if (list[i].id !== id) continue;
    var next = list[i + 1];
    return next ? list[i].min + " \u2013 " + (next.min - 1) + " px" : list[i].min + " px and up";
  }
  return "";
}
function previewWidthOf(app, id) {
  var list = breakpointsOf(app);
  for (var i = 0; i < list.length; i++) {
    if (list[i].id !== id) continue;
    var next = list[i + 1], w = Number(list[i].preview) || list[i].min || 360;
    return Math.max(list[i].min, next ? Math.min(w, next.min - 1) : w);
  }
  return 0;
}
function overrideOf(node, id) {
  var o = node && node.overrides;
  if (!o) return null;
  return o[id] || LEGACY[id] && o[LEGACY[id]] || null;
}
function migrateOverrideKeys(nodes) {
  (nodes || []).forEach(function(n) {
    if (n.overrides) Object.keys(LEGACY).forEach(function(id) {
      var old = LEGACY[id];
      if (!n.overrides[old]) return;
      if (!n.overrides[id]) n.overrides[id] = n.overrides[old];
      delete n.overrides[old];
    });
    migrateOverrideKeys(n.children);
  });
}
function baseOf(node) {
  var b = {};
  OVERRIDABLE.forEach(function(k) {
    if (node && node[k] !== void 0) b[k] = clone4(node[k]);
  });
  return b;
}
function applyOverrides(node, base, chain) {
  OVERRIDABLE.forEach(function(k) {
    if (base[k] === void 0) delete node[k];
    else node[k] = clone4(base[k]);
  });
  (chain || []).forEach(function(id) {
    var o = overrideOf(node, id);
    if (!o) return;
    Object.keys(o).forEach(function(k) {
      if (OVERRIDABLE.indexOf(k) === -1) return;
      node[k] = MERGED[k] && isPlain(o[k]) ? merge(node[k], o[k]) : clone4(o[k]);
    });
  });
  return node;
}
function resolveNode(node, chain, base) {
  var copy = Object.assign({}, node);
  return applyOverrides(copy, base || baseOf(node), chain);
}
function hasOverrides(nodes) {
  return (nodes || []).some(function(n) {
    return n.overrides && Object.keys(n.overrides).some(function(k) {
      return n.overrides[k] && Object.keys(n.overrides[k]).length;
    }) || hasOverrides(n.children);
  });
}
function overrideDiff(inherited, current2) {
  var out = {};
  OVERRIDABLE.forEach(function(k) {
    var a = inherited[k], b = current2[k];
    if (JSON.stringify(a) === JSON.stringify(b)) return;
    if (MERGED[k] && isPlain(a) && isPlain(b)) {
      var d = {};
      Object.keys(b).forEach(function(kk) {
        if (JSON.stringify(a[kk]) !== JSON.stringify(b[kk])) d[kk] = clone4(b[kk]);
      });
      if (Object.keys(d).length) out[k] = d;
      return;
    }
    if (b !== void 0) out[k] = clone4(b);
  });
  return out;
}
function isNoValue(v) {
  return v === void 0 || v === null || v === "???";
}
function applyFallbacks(raw, resolved) {
  var fb = raw && raw.__fallback;
  if (!fb || typeof fb !== "object") return resolved;
  var out = null;
  Object.keys(fb).forEach(function(k) {
    var r = raw[k];
    if (typeof r !== "string" || !/\{[^{}]+\}/.test(r) || fb[k] === void 0) return;
    var v = resolved[k];
    var whole = /^\{[^{}]+\}$/.test(r.trim());
    var empty = isNoValue(v) || v === r || whole && v === "" && /^\{msg\b/.test(r.trim()) || !whole && typeof v === "string" && (/\?\?\?/.test(v) || /\{[^{}]+\}/.test(v));
    if (!empty) return;
    if (!out) out = Object.assign({}, resolved);
    out[k] = clone4(fb[k]);
  });
  return out || resolved;
}

// src/model/migrate.js
var TREE_VERSION = 1;
function genIdFallback() {
  return "n" + Math.random().toString(16).slice(2, 10);
}
function migrateSurface(surface, genId) {
  if (!surface) return surface;
  genId = genId || genIdFallback;
  if (!surface.components) surface.components = [];
  if (!surface.orphans) surface.orphans = [];
  if (!surface.logic) surface.logic = { nodes: [], wires: [] };
  migrateOverrideKeys(surface.components);
  delete surface.breakpoints;
  if (surface.treeVersion >= TREE_VERSION) return surface;
  var layers = (surface.layers || []).map(function(l) {
    return { id: l.id, name: l.name || "Layer", parentId: l.parentId || null, state: l.state || (l.visible === false ? "hide" : "show") };
  });
  var rootLayer = layers[0] || null;
  var layerById = {};
  layers.forEach(function(l) {
    layerById[l.id] = l;
  });
  var effLayer = function(c) {
    return c.layerId && layerById[c.layerId] ? c.layerId : rootLayer ? rootLayer.id : null;
  };
  var groupNode = {};
  var groupCount = 0;
  var flat = [];
  surface.components.forEach(function(c) {
    if (c.g) {
      var g = groupNode[c.g];
      if (!g) {
        groupCount++;
        g = groupNode[c.g] = { id: c.g, type: "@group", name: "Group " + groupCount, x: 0, y: 0, w: 0, h: 0, children: [], layerId: effLayer(c) };
        flat.push(g);
      }
      g.children.push(c);
      delete c.layerId;
    } else {
      flat.push(c);
    }
    delete c.g;
  });
  Object.keys(groupNode).forEach(function(id) {
    fitGroup(groupNode[id]);
  });
  var layerNode = {};
  layers.forEach(function(l) {
    if (rootLayer && l.id === rootLayer.id) return;
    layerNode[l.id] = { id: l.id, type: "@group", name: l.name, x: 0, y: 0, w: 0, h: 0, children: [], visibility: l.state === "show" ? void 0 : l.state };
  });
  var containerOf = function(layerId) {
    return layerId && layerNode[layerId] ? layerNode[layerId] : null;
  };
  var root = [];
  var placedLayers = {};
  var placeLayer = function(layerId) {
    if (!layerNode[layerId] || placedLayers[layerId]) return;
    placedLayers[layerId] = true;
    var parentLayer = layerById[layerId].parentId;
    if (parentLayer && layerNode[parentLayer]) placeLayer(parentLayer);
    var parent = containerOf(parentLayer);
    (parent ? parent.children : root).push(layerNode[layerId]);
  };
  flat.forEach(function(c) {
    var layerId = c.type === "@group" && c.layerId !== void 0 ? c.layerId : effLayer(c);
    delete c.layerId;
    placeLayer(layerId);
    var parent = containerOf(layerId);
    (parent ? parent.children : root).push(c);
  });
  layers.forEach(function(l) {
    placeLayer(l.id);
  });
  if (rootLayer && rootLayer.state && rootLayer.state !== "show") {
    root.forEach(function(n) {
      if (!layerNode[n.id]) n.visibility = rootLayer.state;
    });
  }
  var fitDeep = function(n) {
    (n.children || []).forEach(fitDeep);
    if (layerNode[n.id]) fitGroup(n);
  };
  root.forEach(fitDeep);
  surface.components = root;
  delete surface.layers;
  delete surface.groups;
  surface.treeVersion = TREE_VERSION;
  return surface;
}

// src/model/index.js
function migrateProject(project) {
  if (!project) return project;
  project.screens = Array.isArray(project.screens) ? project.screens : [];
  project.templates = Array.isArray(project.templates) ? project.templates : [];
  project.folders = Array.isArray(project.folders) ? project.folders : [];
  project.flows = Array.isArray(project.flows) ? project.flows : [];
  project.screens.forEach(function(s) {
    migrateSurface(s);
  });
  project.templates.forEach(function(t) {
    migrateSurface(t);
  });
  project.flows.forEach(function(f) {
    if (!f.logic) f.logic = { nodes: [], wires: [] };
  });
  return project;
}
// Annotate the CommonJS export names for ESM import in node:
0 && (module.exports = {
  BindingRef,
  CAROUSEL_DEFAULT,
  CONTAINER_TYPES,
  DEFAULT_BREAKPOINTS,
  DEFAULT_THEME,
  DEVICE_PRESETS,
  H_CONSTRAINTS,
  ITEMS_DEFAULT,
  LAYOUT_MODES,
  NAME_RE,
  OVERLAY_DEFAULT,
  OVERLAY_KINDS,
  OVERRIDABLE,
  PLACES,
  SHADES,
  TEMPLATE_CONTENT_MODES,
  TEMPLATE_LIVE_DEFAULT,
  TOKEN_CATEGORIES,
  TREE_VERSION,
  V_CONSTRAINTS,
  ZOOM_DEFAULT,
  absBox,
  activeBreakpoint,
  alignFraction,
  allDeclarations,
  allNodes,
  ancestors,
  applyFallbacks,
  applyOverrides,
  bandOf,
  baseOf,
  borderOf,
  boxCss,
  breakpointsOf,
  buildInstance,
  canRotate,
  carouselOf,
  carouselSlideSize,
  carouselTrackCss,
  chainFor,
  childBounds,
  childSizing,
  cloneWithNewIds,
  constraintCss,
  constraintsOf,
  contentOrigin,
  currentTheme,
  designBreakpoint,
  detach,
  dockOf,
  effectiveLocked,
  effectiveVisibility,
  find,
  findByName,
  findType,
  fitGroup,
  flowAxis,
  frameCss,
  frameHugs,
  generatePalette,
  getTypes,
  guessConstraints,
  hasAutoLayout,
  hasConstraints,
  hasOverrides,
  hasVariables,
  inSlot,
  inferNodeConstraints,
  innerSize,
  insert,
  isAncestor,
  isBindingRef,
  isContainer,
  isInFlow,
  isNoValue,
  isSlotFrame,
  isSlotHost,
  isTokenRef,
  isTypeRef,
  kids,
  layoutOf,
  listTokens,
  locate,
  makeFrame,
  makeScope,
  marginOf,
  memberAt,
  memberPaths,
  mentionsToken,
  migrateOverrideKeys,
  migrateProject,
  migrateSurface,
  move,
  onScreen,
  overlayBox,
  overlayOf,
  overrideDiff,
  overrideOf,
  paddingOf,
  parentOf,
  parentSize,
  placeOf,
  placeOrphan,
  previewWidthOf,
  rangeOf,
  refitGroupsUp,
  remove,
  resizeWithConstraints,
  resolveNode,
  resolveToken,
  resolveTokenProps,
  resolveTokenValue,
  setTheme,
  setTypes,
  slotOf,
  styleOf,
  surfaceScope,
  syncSlots,
  takesPadding,
  templateContentFit,
  templateContentOf,
  templateLiveOf,
  themeCss,
  themeOf,
  tidyContainer,
  tokenCss,
  tokenPathOf,
  tokenVar,
  tokenVarName,
  tracksCss,
  unwrap,
  variableValue,
  visibleVariables,
  walk,
  wrapIn,
  wrapInGroup,
  zOf,
  zoomOf
});
