// AUTO-GENERATED by build.js from src/model/index.js — DO NOT EDIT THIS FILE.
// Edit the source instead, then run `npm run build` (or `npm run watch`).
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/model/index.js
var index_exports = {};
__export(index_exports, {
  CONTAINER_TYPES: () => CONTAINER_TYPES,
  H_CONSTRAINTS: () => H_CONSTRAINTS,
  LAYOUT_MODES: () => LAYOUT_MODES,
  TREE_VERSION: () => TREE_VERSION,
  V_CONSTRAINTS: () => V_CONSTRAINTS,
  absBox: () => absBox,
  allNodes: () => allNodes,
  ancestors: () => ancestors,
  boxCss: () => boxCss,
  canRotate: () => canRotate,
  childBounds: () => childBounds,
  childSizing: () => childSizing,
  cloneWithNewIds: () => cloneWithNewIds,
  constraintCss: () => constraintCss,
  constraintsOf: () => constraintsOf,
  detach: () => detach,
  effectiveLocked: () => effectiveLocked,
  effectiveVisibility: () => effectiveVisibility,
  find: () => find,
  findByName: () => findByName,
  fitGroup: () => fitGroup,
  frameCss: () => frameCss,
  frameHugs: () => frameHugs,
  hasAutoLayout: () => hasAutoLayout,
  hasConstraints: () => hasConstraints,
  innerSize: () => innerSize,
  insert: () => insert,
  isAncestor: () => isAncestor,
  isContainer: () => isContainer,
  isInFlow: () => isInFlow,
  kids: () => kids,
  layoutOf: () => layoutOf,
  locate: () => locate,
  makeFrame: () => makeFrame,
  migrateProject: () => migrateProject,
  migrateSurface: () => migrateSurface,
  move: () => move,
  parentOf: () => parentOf,
  parentSize: () => parentSize,
  placeOrphan: () => placeOrphan,
  refitGroupsUp: () => refitGroupsUp,
  remove: () => remove,
  resizeWithConstraints: () => resizeWithConstraints,
  styleOf: () => styleOf,
  tidyContainer: () => tidyContainer,
  tracksCss: () => tracksCss,
  unwrap: () => unwrap,
  walk: () => walk,
  wrapIn: () => wrapIn,
  wrapInGroup: () => wrapInGroup
});
module.exports = __toCommonJS(index_exports);

// src/model/tree.js
var CONTAINER_TYPES = { "@group": true, "@frame": true };
function isContainer(node) {
  return !!(node && CONTAINER_TYPES[node.type]);
}
function kids(node) {
  return node && node.children || [];
}
function listOf(surface, parent) {
  if (!parent) return surface.components || (surface.components = []);
  return parent.children || (parent.children = []);
}
function walk(surface, fn, opts) {
  var stop = false;
  function visit(list, parent, depth) {
    for (var i = 0; i < list.length && !stop; i++) {
      var node = list[i];
      var r = fn(node, parent, i, depth);
      if (r === "stop") {
        stop = true;
        return;
      }
      if (r !== false && node.children) visit(node.children, node, depth + 1);
    }
  }
  visit(surface && surface.components || [], null, 0);
  if (opts && opts.orphans && surface && surface.orphans) visit(surface.orphans, null, 0);
}
function allNodes(surface, opts) {
  var out = [];
  walk(surface, function(n) {
    out.push(n);
  }, opts);
  return out;
}
function locate(surface, id) {
  var found = null;
  function search(list, parent, orphan) {
    for (var i = 0; i < list.length; i++) {
      var n = list[i];
      if (n.id === id) {
        found = { node: n, parent, list, index: i, orphan };
        return true;
      }
      if (n.children && search(n.children, n, orphan)) return true;
    }
    return false;
  }
  if (!surface) return null;
  if (!search(surface.components || [], null, false) && surface.orphans) search(surface.orphans, null, true);
  return found;
}
function find(surface, id) {
  var loc = locate(surface, id);
  return loc ? loc.node : null;
}
function parentOf(surface, id) {
  var loc = locate(surface, id);
  return loc ? loc.parent : null;
}
function ancestors(surface, id) {
  var chain = [];
  var loc = locate(surface, id);
  while (loc && loc.parent) {
    chain.unshift(loc.parent);
    loc = locate(surface, loc.parent.id);
  }
  return chain;
}
function isAncestor(surface, ancestorId, id) {
  return ancestors(surface, id).some(function(a) {
    return a.id === ancestorId;
  });
}
function insert(surface, parentId, index, node) {
  var parent = parentId ? find(surface, parentId) : null;
  if (parentId && !isContainer(parent)) throw new Error("[nexa] insert: " + parentId + " is not a container");
  var list = listOf(surface, parent);
  var at = index === void 0 || index === null || index > list.length ? list.length : Math.max(0, index);
  list.splice(at, 0, node);
  return node;
}
function detach(surface, id) {
  var loc = locate(surface, id);
  if (!loc) return null;
  loc.list.splice(loc.index, 1);
  return { node: loc.node, parentId: loc.parent ? loc.parent.id : null, index: loc.index, orphan: loc.orphan };
}
function move(surface, id, parentId, index) {
  if (parentId && (parentId === id || isAncestor(surface, id, parentId))) throw new Error("[nexa] move: a node can't go inside itself");
  var d = detach(surface, id);
  if (!d) return null;
  if (d.parentId === (parentId || null) && !d.orphan && index !== void 0 && index !== null && index > d.index) index--;
  insert(surface, parentId || null, index, d.node);
  return d.node;
}
function remove(surface, id) {
  var loc = locate(surface, id);
  var origin = loc && !loc.orphan ? absBox(surface, id) : { x: loc && loc.node.x || 0, y: loc && loc.node.y || 0 };
  var d = detach(surface, id);
  if (!d) return null;
  if (isContainer(d.node) && d.node.children && d.node.children.length) {
    surface.orphans = surface.orphans || [];
    d.node.children.forEach(function(c) {
      c.x = (c.x || 0) + origin.x;
      c.y = (c.y || 0) + origin.y;
      surface.orphans.push(c);
    });
    d.node.children = [];
  }
  return d.node;
}
function placeOrphan(surface, id, parentId, index) {
  var i = (surface.orphans || []).findIndex(function(n) {
    return n.id === id;
  });
  if (i === -1) return null;
  var node = surface.orphans.splice(i, 1)[0];
  insert(surface, parentId || null, index, node);
  return node;
}
function cloneWithNewIds(node, genId) {
  var copy = JSON.parse(JSON.stringify(node));
  (function renew(n) {
    n.id = genId();
    (n.children || []).forEach(renew);
  })(copy);
  return copy;
}
function absBox(surface, id) {
  var loc = locate(surface, id);
  if (!loc) return null;
  var n = loc.node;
  var x = n.x || 0, y = n.y || 0;
  ancestors(surface, id).forEach(function(a) {
    x += a.x || 0;
    y += a.y || 0;
  });
  return { x, y, w: n.w || 0, h: n.h || 0 };
}
function parentSize(surface, id) {
  var p = parentOf(surface, id);
  return p ? { w: p.w || 0, h: p.h || 0 } : { w: surface.width || 0, h: surface.height || 0 };
}
function childBounds(node) {
  var list = kids(node);
  if (!list.length) return null;
  var minX = Infinity, minY = Infinity, maxX = -Infinity, maxY = -Infinity;
  list.forEach(function(c) {
    minX = Math.min(minX, c.x || 0);
    minY = Math.min(minY, c.y || 0);
    maxX = Math.max(maxX, (c.x || 0) + (c.w || 0));
    maxY = Math.max(maxY, (c.y || 0) + (c.h || 0));
  });
  return { x: minX, y: minY, w: maxX - minX, h: maxY - minY };
}
function fitGroup(group) {
  if (!group || group.type !== "@group") return group;
  var b = childBounds(group);
  if (!b) return group;
  if (b.x !== 0 || b.y !== 0) {
    kids(group).forEach(function(c) {
      c.x = (c.x || 0) - b.x;
      c.y = (c.y || 0) - b.y;
    });
    group.x = (group.x || 0) + b.x;
    group.y = (group.y || 0) + b.y;
  }
  group.w = b.w;
  group.h = b.h;
  return group;
}
function refitGroupsUp(surface, id) {
  ancestors(surface, id).reverse().forEach(function(a) {
    if (a.type === "@group") fitGroup(a);
  });
}
function tidyContainer(surface, id) {
  var dropped = [];
  var loc = id ? locate(surface, id) : null;
  while (loc && !loc.orphan && loc.node.type === "@group" && !kids(loc.node).length) {
    var parentId = loc.parent ? loc.parent.id : null;
    loc.list.splice(loc.index, 1);
    dropped.push(loc.node.id);
    loc = parentId ? locate(surface, parentId) : null;
  }
  if (loc && !loc.orphan) {
    fitGroup(loc.node);
    refitGroupsUp(surface, loc.node.id);
  }
  return dropped;
}
function wrapIn(surface, ids, container) {
  return wrapInGroup(surface, ids, container);
}
function wrapInGroup(surface, ids, group) {
  var locs = ids.map(function(id) {
    return locate(surface, id);
  }).filter(Boolean);
  if (!locs.length) return null;
  var parent = locs[0].parent;
  if (locs.some(function(l) {
    return l.parent !== parent || l.orphan;
  })) throw new Error("[nexa] wrap: nodes must share one parent");
  locs.sort(function(a, b2) {
    return a.index - b2.index;
  });
  var at = locs[locs.length - 1].index - (locs.length - 1);
  var list = listOf(surface, parent);
  locs.slice().reverse().forEach(function(l) {
    list.splice(l.index, 1);
  });
  group.type = group.type === "@frame" ? "@frame" : "@group";
  group.children = locs.map(function(l) {
    return l.node;
  });
  group.x = 0;
  group.y = 0;
  var b = childBounds(group);
  kids(group).forEach(function(c) {
    c.x = (c.x || 0) - b.x;
    c.y = (c.y || 0) - b.y;
  });
  group.x = b.x;
  group.y = b.y;
  group.w = b.w;
  group.h = b.h;
  list.splice(at, 0, group);
  return group;
}
function unwrap(surface, id) {
  var loc = locate(surface, id);
  if (!loc || !isContainer(loc.node)) return [];
  var g = loc.node;
  var children = kids(g);
  children.forEach(function(c) {
    c.x = (c.x || 0) + (g.x || 0);
    c.y = (c.y || 0) + (g.y || 0);
  });
  loc.list.splice.apply(loc.list, [loc.index, 1].concat(children));
  return children;
}
var VIS_RANK = { show: 0, hide: 1, remove: 2 };
function effectiveVisibility(surface, id) {
  var chain = ancestors(surface, id).concat([find(surface, id)]);
  var eff = "show";
  chain.forEach(function(n) {
    var v = n && n.visibility || "show";
    if (VIS_RANK[v] > VIS_RANK[eff]) eff = v;
  });
  return eff;
}
function effectiveLocked(surface, id) {
  return ancestors(surface, id).concat([find(surface, id)]).some(function(n) {
    return n && n.locked;
  });
}
function findByName(surface, name) {
  var out = [];
  walk(surface, function(n) {
    if (isContainer(n) && n.name === name) out.push(n);
  });
  return out;
}

// src/model/layout.js
var LAYOUT_MODES = ["none", "horizontal", "vertical", "grid"];
var DEFAULT_LAYOUT = {
  mode: "none",
  padding: { t: 0, r: 0, b: 0, l: 0 },
  gap: 0,
  rowGap: void 0,
  // unset: the same as gap
  alignX: "start",
  alignY: "start",
  wrap: false,
  columns: [{ size: 1, unit: "fr" }, { size: 1, unit: "fr" }],
  rows: [],
  sizeW: "fixed",
  sizeH: "fixed"
};
var DEFAULT_STYLE = { fill: "", stroke: "", strokeWidth: 0, radius: 0, clip: false };
function num(v, d) {
  var n = typeof v === "number" ? v : parseFloat(v);
  return isFinite(n) ? n : d || 0;
}
function layoutOf(frame) {
  var l = frame && frame.layout || {};
  var out = {};
  Object.keys(DEFAULT_LAYOUT).forEach(function(k) {
    out[k] = l[k] !== void 0 ? l[k] : DEFAULT_LAYOUT[k];
  });
  var p = out.padding || {};
  out.padding = { t: num(p.t), r: num(p.r), b: num(p.b), l: num(p.l) };
  if (LAYOUT_MODES.indexOf(out.mode) === -1) out.mode = "none";
  if (!Array.isArray(out.columns)) out.columns = DEFAULT_LAYOUT.columns;
  if (!Array.isArray(out.rows)) out.rows = [];
  return out;
}
function styleOf(frame) {
  var s = frame && frame.style || {};
  var out = {};
  Object.keys(DEFAULT_STYLE).forEach(function(k) {
    out[k] = s[k] !== void 0 ? s[k] : DEFAULT_STYLE[k];
  });
  return out;
}
function hasAutoLayout(node) {
  return !!node && node.type === "@frame" && layoutOf(node).mode !== "none";
}
function isInFlow(child, parent) {
  return hasAutoLayout(parent) && !(child && child.layoutChild && child.layoutChild.absolute);
}
function childSizing(child, axis) {
  var lc = child && child.layoutChild || {};
  var v = lc[axis];
  if (v === "fill") return "fill";
  if (v === "hug" && hasAutoLayout(child)) return "hug";
  return "fixed";
}
function frameHugs(frame, axis) {
  if (!hasAutoLayout(frame)) return false;
  var l = layoutOf(frame);
  return (axis === "w" ? l.sizeW : l.sizeH) === "hug";
}
var FLEX_ALIGN = { start: "flex-start", center: "center", end: "flex-end" };
function track(t) {
  if (!t) return "1fr";
  if (t.unit === "auto") return "auto";
  var size = num(t.size, 1);
  return t.unit === "px" ? size + "px" : size + "fr";
}
function tracksCss(list) {
  return (list || []).map(track).join(" ");
}
function frameCss(frame) {
  var l = layoutOf(frame);
  var s = styleOf(frame);
  var css = {
    background: s.fill || "",
    border: num(s.strokeWidth) > 0 && s.stroke ? num(s.strokeWidth) + "px solid " + s.stroke : "",
    "border-radius": num(s.radius) ? num(s.radius) + "px" : "",
    overflow: s.clip ? "hidden" : "",
    "box-sizing": "border-box"
  };
  if (l.mode === "none") {
    css.display = "";
    css.padding = "";
    return css;
  }
  css.padding = l.padding.t + "px " + l.padding.r + "px " + l.padding.b + "px " + l.padding.l + "px";
  if (l.mode === "grid") {
    css.display = "grid";
    css["grid-template-columns"] = tracksCss(l.columns) || "1fr";
    css["grid-template-rows"] = tracksCss(l.rows);
    css["grid-auto-rows"] = "auto";
    css["column-gap"] = num(l.gap) + "px";
    css["row-gap"] = num(l.rowGap !== void 0 && l.rowGap !== "" ? l.rowGap : l.gap) + "px";
    css["justify-items"] = l.alignX;
    css["align-items"] = l.alignY;
    css["align-content"] = l.alignY;
    css["justify-content"] = l.alignX;
  } else {
    var horizontal = l.mode === "horizontal";
    var main = horizontal ? l.alignX : l.alignY;
    var cross = horizontal ? l.alignY : l.alignX;
    css.display = "flex";
    css["flex-direction"] = horizontal ? "row" : "column";
    css["flex-wrap"] = horizontal && l.wrap ? "wrap" : "nowrap";
    css["justify-content"] = l.gap === "auto" ? "space-between" : FLEX_ALIGN[main] || "flex-start";
    css["align-items"] = FLEX_ALIGN[cross] || "flex-start";
    css["align-content"] = FLEX_ALIGN[horizontal ? l.alignY : l.alignX] || "flex-start";
    var gap = l.gap === "auto" ? 0 : num(l.gap);
    css[horizontal ? "column-gap" : "row-gap"] = gap + "px";
    css[horizontal ? "row-gap" : "column-gap"] = (horizontal && l.wrap ? num(l.rowGap !== void 0 && l.rowGap !== "" ? l.rowGap : l.gap) : 0) + "px";
  }
  return css;
}
var H_CONSTRAINTS = ["left", "right", "leftRight", "center", "scale"];
var V_CONSTRAINTS = ["top", "bottom", "topBottom", "center", "scale"];
function constraintsOf(node) {
  var c = node && node.constraints || {};
  return { h: H_CONSTRAINTS.indexOf(c.h) === -1 ? "left" : c.h, v: V_CONSTRAINTS.indexOf(c.v) === -1 ? "top" : c.v };
}
function hasConstraints(node, parent) {
  return (!parent || parent.type === "@frame") && !isInFlow(node, parent);
}
function innerSize(frame) {
  var s = styleOf(frame);
  var bw = num(s.strokeWidth) > 0 && s.stroke ? num(s.strokeWidth) : 0;
  return { w: num(frame.w) - 2 * bw, h: num(frame.h) - 2 * bw };
}
function axisCss(mode, pos, size, parentSize2, startProp, endProp, sizeProp) {
  var css = {};
  var end = parentSize2 - pos - size;
  css[startProp] = pos + "px";
  css[endProp] = "";
  css[sizeProp] = size + "px";
  if (mode === "right" || mode === "bottom") {
    css[startProp] = "auto";
    css[endProp] = end + "px";
  } else if (mode === "leftRight" || mode === "topBottom") {
    css[endProp] = end + "px";
    css[sizeProp] = "auto";
  } else if (mode === "center") css[startProp] = "calc(50% + " + (pos - parentSize2 / 2) + "px)";
  else if (mode === "scale" && parentSize2 > 0) {
    css[startProp] = pos / parentSize2 * 100 + "%";
    css[sizeProp] = size / parentSize2 * 100 + "%";
  }
  return css;
}
function constraintCss(node, parentSize2) {
  var c = constraintsOf(node);
  var h = axisCss(c.h, num(node.x), num(node.w), parentSize2.w, "left", "right", "width");
  var v = axisCss(c.v, num(node.y), num(node.h), parentSize2.h, "top", "bottom", "height");
  return Object.assign(h, v);
}
function axisResize(mode, pos, size, oldP, newP) {
  var d = newP - oldP;
  if (mode === "right" || mode === "bottom") return [pos + d, size];
  if (mode === "leftRight" || mode === "topBottom") return [pos, Math.max(1, size + d)];
  if (mode === "center") return [pos + d / 2, size];
  if (mode === "scale" && oldP > 0) return [pos * newP / oldP, Math.max(1, size * newP / oldP)];
  return [pos, size];
}
function resizeWithConstraints(box, constraints, oldP, newP) {
  var c = constraints || { h: "left", v: "top" };
  var h = axisResize(c.h, box.x, box.w, oldP.w, newP.w);
  var v = axisResize(c.v, box.y, box.h, oldP.h, newP.h);
  return { x: Math.round(h[0]), y: Math.round(v[0]), w: Math.round(h[1]), h: Math.round(v[1]) };
}
function boxCss(node, parent, opts) {
  var css = {
    position: "absolute",
    left: num(node.x) + "px",
    top: num(node.y) + "px",
    width: num(node.w) + "px",
    height: num(node.h) + "px",
    right: "",
    bottom: "",
    flex: "",
    "align-self": "",
    "justify-self": "",
    "grid-column": "",
    "grid-row": "",
    "min-width": node.minW ? num(node.minW) + "px" : "",
    "max-width": node.maxW ? num(node.maxW) + "px" : "",
    "min-height": node.minH ? num(node.minH) + "px" : "",
    "max-height": node.maxH ? num(node.maxH) + "px" : ""
  };
  if (opts && opts.constraints && hasConstraints(node, parent)) {
    var ps = parent ? innerSize(parent) : opts.parentSize;
    var c = constraintsOf(node);
    if (ps && (c.h !== "left" || c.v !== "top")) Object.assign(css, constraintCss(node, ps));
  }
  if (frameHugs(node, "w")) css.width = "max-content";
  if (frameHugs(node, "h")) css.height = "max-content";
  if (!isInFlow(node, parent)) return css;
  var mode = layoutOf(parent).mode;
  var sw = childSizing(node, "w"), sh = childSizing(node, "h");
  css.position = "relative";
  css.left = "auto";
  css.top = "auto";
  css.right = "";
  css.bottom = "";
  if (mode === "grid") {
    var lc = node.layoutChild || {};
    if (lc.col) css["grid-column"] = num(lc.col, 1) + (lc.colSpan > 1 ? " / span " + num(lc.colSpan, 1) : "");
    else if (lc.colSpan > 1) css["grid-column"] = "span " + num(lc.colSpan, 1);
    if (lc.row) css["grid-row"] = num(lc.row, 1) + (lc.rowSpan > 1 ? " / span " + num(lc.rowSpan, 1) : "");
    else if (lc.rowSpan > 1) css["grid-row"] = "span " + num(lc.rowSpan, 1);
    if (sw === "fill") {
      css.width = "auto";
      css["justify-self"] = "stretch";
    } else if (sw === "hug") css.width = "max-content";
    if (sh === "fill") {
      css.height = "auto";
      css["align-self"] = "stretch";
    } else if (sh === "hug") css.height = "max-content";
    return css;
  }
  var horizontal = mode === "horizontal";
  var mainSizing = horizontal ? sw : sh, crossSizing = horizontal ? sh : sw;
  var mainProp = horizontal ? "width" : "height", crossProp = horizontal ? "height" : "width";
  if (mainSizing === "fill") {
    css.flex = "1 1 0px";
    css[mainProp] = "auto";
    css[horizontal ? "min-width" : "min-height"] = css[horizontal ? "min-width" : "min-height"] || "0px";
  } else {
    css.flex = "0 0 auto";
    if (mainSizing === "hug") css[mainProp] = "max-content";
  }
  if (crossSizing === "fill") {
    css["align-self"] = "stretch";
    css[crossProp] = "auto";
  } else if (crossSizing === "hug") css[crossProp] = "max-content";
  return css;
}
function canRotate(node, parent) {
  return !isInFlow(node, parent);
}
function makeFrame(mode, w, h) {
  var frame = { type: "@frame", w: w || 240, h: h || 160, children: [], style: { fill: "#ffffff", stroke: "#d0d0d0", strokeWidth: 1, radius: 4, clip: false } };
  if (mode && mode !== "none") {
    frame.layout = { mode, padding: { t: 8, r: 8, b: 8, l: 8 }, gap: 8 };
    if (mode === "grid") frame.layout.columns = [{ size: 1, unit: "fr" }, { size: 1, unit: "fr" }];
  }
  return frame;
}

// src/model/migrate.js
var TREE_VERSION = 1;
function genIdFallback() {
  return "n" + Math.random().toString(16).slice(2, 10);
}
function migrateSurface(surface, genId) {
  if (!surface) return surface;
  genId = genId || genIdFallback;
  if (!surface.components) surface.components = [];
  if (!surface.orphans) surface.orphans = [];
  if (!surface.logic) surface.logic = { nodes: [], wires: [] };
  if (surface.treeVersion >= TREE_VERSION) return surface;
  var layers = (surface.layers || []).map(function(l) {
    return { id: l.id, name: l.name || "Layer", parentId: l.parentId || null, state: l.state || (l.visible === false ? "hide" : "show") };
  });
  var rootLayer = layers[0] || null;
  var layerById = {};
  layers.forEach(function(l) {
    layerById[l.id] = l;
  });
  var effLayer = function(c) {
    return c.layerId && layerById[c.layerId] ? c.layerId : rootLayer ? rootLayer.id : null;
  };
  var groupNode = {};
  var groupCount = 0;
  var flat = [];
  surface.components.forEach(function(c) {
    if (c.g) {
      var g = groupNode[c.g];
      if (!g) {
        groupCount++;
        g = groupNode[c.g] = { id: c.g, type: "@group", name: "Group " + groupCount, x: 0, y: 0, w: 0, h: 0, children: [], layerId: effLayer(c) };
        flat.push(g);
      }
      g.children.push(c);
      delete c.layerId;
    } else {
      flat.push(c);
    }
    delete c.g;
  });
  Object.keys(groupNode).forEach(function(id) {
    fitGroup(groupNode[id]);
  });
  var layerNode = {};
  layers.forEach(function(l) {
    if (rootLayer && l.id === rootLayer.id) return;
    layerNode[l.id] = { id: l.id, type: "@group", name: l.name, x: 0, y: 0, w: 0, h: 0, children: [], visibility: l.state === "show" ? void 0 : l.state };
  });
  var containerOf = function(layerId) {
    return layerId && layerNode[layerId] ? layerNode[layerId] : null;
  };
  var root = [];
  var placedLayers = {};
  var placeLayer = function(layerId) {
    if (!layerNode[layerId] || placedLayers[layerId]) return;
    placedLayers[layerId] = true;
    var parentLayer = layerById[layerId].parentId;
    if (parentLayer && layerNode[parentLayer]) placeLayer(parentLayer);
    var parent = containerOf(parentLayer);
    (parent ? parent.children : root).push(layerNode[layerId]);
  };
  flat.forEach(function(c) {
    var layerId = c.type === "@group" && c.layerId !== void 0 ? c.layerId : effLayer(c);
    delete c.layerId;
    placeLayer(layerId);
    var parent = containerOf(layerId);
    (parent ? parent.children : root).push(c);
  });
  layers.forEach(function(l) {
    placeLayer(l.id);
  });
  if (rootLayer && rootLayer.state && rootLayer.state !== "show") {
    root.forEach(function(n) {
      if (!layerNode[n.id]) n.visibility = rootLayer.state;
    });
  }
  var fitDeep = function(n) {
    (n.children || []).forEach(fitDeep);
    if (layerNode[n.id]) fitGroup(n);
  };
  root.forEach(fitDeep);
  surface.components = root;
  delete surface.layers;
  delete surface.groups;
  surface.treeVersion = TREE_VERSION;
  return surface;
}

// src/model/index.js
function migrateProject(project) {
  if (!project) return project;
  (project.screens || []).forEach(function(s) {
    migrateSurface(s);
  });
  (project.templates || []).forEach(function(t) {
    migrateSurface(t);
  });
  return project;
}
// Annotate the CommonJS export names for ESM import in node:
0 && (module.exports = {
  CONTAINER_TYPES,
  H_CONSTRAINTS,
  LAYOUT_MODES,
  TREE_VERSION,
  V_CONSTRAINTS,
  absBox,
  allNodes,
  ancestors,
  boxCss,
  canRotate,
  childBounds,
  childSizing,
  cloneWithNewIds,
  constraintCss,
  constraintsOf,
  detach,
  effectiveLocked,
  effectiveVisibility,
  find,
  findByName,
  fitGroup,
  frameCss,
  frameHugs,
  hasAutoLayout,
  hasConstraints,
  innerSize,
  insert,
  isAncestor,
  isContainer,
  isInFlow,
  kids,
  layoutOf,
  locate,
  makeFrame,
  migrateProject,
  migrateSurface,
  move,
  parentOf,
  parentSize,
  placeOrphan,
  refitGroupsUp,
  remove,
  resizeWithConstraints,
  styleOf,
  tidyContainer,
  tracksCss,
  unwrap,
  walk,
  wrapIn,
  wrapInGroup
});
