// AUTO-GENERATED by build.js from src/model/index.js — DO NOT EDIT THIS FILE.
// Edit the source instead, then run `npm run build` (or `npm run watch`).
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/model/index.js
var index_exports = {};
__export(index_exports, {
  CONTAINER_TYPES: () => CONTAINER_TYPES,
  TREE_VERSION: () => TREE_VERSION,
  absBox: () => absBox,
  allNodes: () => allNodes,
  ancestors: () => ancestors,
  childBounds: () => childBounds,
  cloneWithNewIds: () => cloneWithNewIds,
  detach: () => detach,
  effectiveLocked: () => effectiveLocked,
  effectiveVisibility: () => effectiveVisibility,
  find: () => find,
  findByName: () => findByName,
  fitGroup: () => fitGroup,
  insert: () => insert,
  isAncestor: () => isAncestor,
  isContainer: () => isContainer,
  kids: () => kids,
  locate: () => locate,
  migrateProject: () => migrateProject,
  migrateSurface: () => migrateSurface,
  move: () => move,
  parentOf: () => parentOf,
  parentSize: () => parentSize,
  placeOrphan: () => placeOrphan,
  refitGroupsUp: () => refitGroupsUp,
  remove: () => remove,
  unwrap: () => unwrap,
  walk: () => walk,
  wrapInGroup: () => wrapInGroup
});
module.exports = __toCommonJS(index_exports);

// src/model/tree.js
var CONTAINER_TYPES = { "@group": true, "@frame": true };
function isContainer(node) {
  return !!(node && CONTAINER_TYPES[node.type]);
}
function kids(node) {
  return node && node.children || [];
}
function listOf(surface, parent) {
  if (!parent) return surface.components || (surface.components = []);
  return parent.children || (parent.children = []);
}
function walk(surface, fn, opts) {
  var stop = false;
  function visit(list, parent, depth) {
    for (var i = 0; i < list.length && !stop; i++) {
      var node = list[i];
      var r = fn(node, parent, i, depth);
      if (r === "stop") {
        stop = true;
        return;
      }
      if (r !== false && node.children) visit(node.children, node, depth + 1);
    }
  }
  visit(surface && surface.components || [], null, 0);
  if (opts && opts.orphans && surface && surface.orphans) visit(surface.orphans, null, 0);
}
function allNodes(surface, opts) {
  var out = [];
  walk(surface, function(n) {
    out.push(n);
  }, opts);
  return out;
}
function locate(surface, id) {
  var found = null;
  function search(list, parent, orphan) {
    for (var i = 0; i < list.length; i++) {
      var n = list[i];
      if (n.id === id) {
        found = { node: n, parent, list, index: i, orphan };
        return true;
      }
      if (n.children && search(n.children, n, orphan)) return true;
    }
    return false;
  }
  if (!surface) return null;
  if (!search(surface.components || [], null, false) && surface.orphans) search(surface.orphans, null, true);
  return found;
}
function find(surface, id) {
  var loc = locate(surface, id);
  return loc ? loc.node : null;
}
function parentOf(surface, id) {
  var loc = locate(surface, id);
  return loc ? loc.parent : null;
}
function ancestors(surface, id) {
  var chain = [];
  var loc = locate(surface, id);
  while (loc && loc.parent) {
    chain.unshift(loc.parent);
    loc = locate(surface, loc.parent.id);
  }
  return chain;
}
function isAncestor(surface, ancestorId, id) {
  return ancestors(surface, id).some(function(a) {
    return a.id === ancestorId;
  });
}
function insert(surface, parentId, index, node) {
  var parent = parentId ? find(surface, parentId) : null;
  if (parentId && !isContainer(parent)) throw new Error("[nexa] insert: " + parentId + " is not a container");
  var list = listOf(surface, parent);
  var at = index === void 0 || index === null || index > list.length ? list.length : Math.max(0, index);
  list.splice(at, 0, node);
  return node;
}
function detach(surface, id) {
  var loc = locate(surface, id);
  if (!loc) return null;
  loc.list.splice(loc.index, 1);
  return { node: loc.node, parentId: loc.parent ? loc.parent.id : null, index: loc.index, orphan: loc.orphan };
}
function move(surface, id, parentId, index) {
  if (parentId && (parentId === id || isAncestor(surface, id, parentId))) throw new Error("[nexa] move: a node can't go inside itself");
  var d = detach(surface, id);
  if (!d) return null;
  if (d.parentId === (parentId || null) && !d.orphan && index !== void 0 && index !== null && index > d.index) index--;
  insert(surface, parentId || null, index, d.node);
  return d.node;
}
function remove(surface, id) {
  var d = detach(surface, id);
  if (!d) return null;
  if (isContainer(d.node) && d.node.children && d.node.children.length) {
    surface.orphans = surface.orphans || [];
    d.node.children.forEach(function(c) {
      surface.orphans.push(c);
    });
    d.node.children = [];
  }
  return d.node;
}
function placeOrphan(surface, id, parentId, index) {
  var i = (surface.orphans || []).findIndex(function(n) {
    return n.id === id;
  });
  if (i === -1) return null;
  var node = surface.orphans.splice(i, 1)[0];
  insert(surface, parentId || null, index, node);
  return node;
}
function cloneWithNewIds(node, genId) {
  var copy = JSON.parse(JSON.stringify(node));
  (function renew(n) {
    n.id = genId();
    (n.children || []).forEach(renew);
  })(copy);
  return copy;
}
function absBox(surface, id) {
  var loc = locate(surface, id);
  if (!loc) return null;
  var n = loc.node;
  var x = n.x || 0, y = n.y || 0;
  ancestors(surface, id).forEach(function(a) {
    x += a.x || 0;
    y += a.y || 0;
  });
  return { x, y, w: n.w || 0, h: n.h || 0 };
}
function parentSize(surface, id) {
  var p = parentOf(surface, id);
  return p ? { w: p.w || 0, h: p.h || 0 } : { w: surface.width || 0, h: surface.height || 0 };
}
function childBounds(node) {
  var list = kids(node);
  if (!list.length) return null;
  var minX = Infinity, minY = Infinity, maxX = -Infinity, maxY = -Infinity;
  list.forEach(function(c) {
    minX = Math.min(minX, c.x || 0);
    minY = Math.min(minY, c.y || 0);
    maxX = Math.max(maxX, (c.x || 0) + (c.w || 0));
    maxY = Math.max(maxY, (c.y || 0) + (c.h || 0));
  });
  return { x: minX, y: minY, w: maxX - minX, h: maxY - minY };
}
function fitGroup(group) {
  if (!group || group.type !== "@group") return group;
  var b = childBounds(group);
  if (!b) return group;
  if (b.x !== 0 || b.y !== 0) {
    kids(group).forEach(function(c) {
      c.x = (c.x || 0) - b.x;
      c.y = (c.y || 0) - b.y;
    });
    group.x = (group.x || 0) + b.x;
    group.y = (group.y || 0) + b.y;
  }
  group.w = b.w;
  group.h = b.h;
  return group;
}
function refitGroupsUp(surface, id) {
  ancestors(surface, id).reverse().forEach(function(a) {
    if (a.type === "@group") fitGroup(a);
  });
}
function wrapInGroup(surface, ids, group) {
  var locs = ids.map(function(id) {
    return locate(surface, id);
  }).filter(Boolean);
  if (!locs.length) return null;
  var parent = locs[0].parent;
  if (locs.some(function(l) {
    return l.parent !== parent || l.orphan;
  })) throw new Error("[nexa] wrap: nodes must share one parent");
  locs.sort(function(a, b) {
    return a.index - b.index;
  });
  var at = locs[locs.length - 1].index - (locs.length - 1);
  var list = listOf(surface, parent);
  locs.slice().reverse().forEach(function(l) {
    list.splice(l.index, 1);
  });
  group.type = "@group";
  group.children = locs.map(function(l) {
    return l.node;
  });
  group.x = 0;
  group.y = 0;
  fitGroup(group);
  list.splice(at, 0, group);
  return group;
}
function unwrap(surface, id) {
  var loc = locate(surface, id);
  if (!loc || !isContainer(loc.node)) return [];
  var g = loc.node;
  var children = kids(g);
  children.forEach(function(c) {
    c.x = (c.x || 0) + (g.x || 0);
    c.y = (c.y || 0) + (g.y || 0);
  });
  loc.list.splice.apply(loc.list, [loc.index, 1].concat(children));
  return children;
}
var VIS_RANK = { show: 0, hide: 1, remove: 2 };
function effectiveVisibility(surface, id) {
  var chain = ancestors(surface, id).concat([find(surface, id)]);
  var eff = "show";
  chain.forEach(function(n) {
    var v = n && n.visibility || "show";
    if (VIS_RANK[v] > VIS_RANK[eff]) eff = v;
  });
  return eff;
}
function effectiveLocked(surface, id) {
  return ancestors(surface, id).concat([find(surface, id)]).some(function(n) {
    return n && n.locked;
  });
}
function findByName(surface, name) {
  var out = [];
  walk(surface, function(n) {
    if (isContainer(n) && n.name === name) out.push(n);
  });
  return out;
}

// src/model/migrate.js
var TREE_VERSION = 1;
function genIdFallback() {
  return "n" + Math.random().toString(16).slice(2, 10);
}
function migrateSurface(surface, genId) {
  if (!surface) return surface;
  genId = genId || genIdFallback;
  if (!surface.components) surface.components = [];
  if (!surface.orphans) surface.orphans = [];
  if (!surface.logic) surface.logic = { nodes: [], wires: [] };
  if (surface.treeVersion >= TREE_VERSION) return surface;
  var layers = (surface.layers || []).map(function(l) {
    return { id: l.id, name: l.name || "Layer", parentId: l.parentId || null, state: l.state || (l.visible === false ? "hide" : "show") };
  });
  var rootLayer = layers[0] || null;
  var layerById = {};
  layers.forEach(function(l) {
    layerById[l.id] = l;
  });
  var effLayer = function(c) {
    return c.layerId && layerById[c.layerId] ? c.layerId : rootLayer ? rootLayer.id : null;
  };
  var groupNode = {};
  var groupCount = 0;
  var flat = [];
  surface.components.forEach(function(c) {
    if (c.g) {
      var g = groupNode[c.g];
      if (!g) {
        groupCount++;
        g = groupNode[c.g] = { id: c.g, type: "@group", name: "Group " + groupCount, x: 0, y: 0, w: 0, h: 0, children: [], layerId: effLayer(c) };
        flat.push(g);
      }
      g.children.push(c);
      delete c.layerId;
    } else {
      flat.push(c);
    }
    delete c.g;
  });
  Object.keys(groupNode).forEach(function(id) {
    fitGroup(groupNode[id]);
  });
  var layerNode = {};
  layers.forEach(function(l) {
    if (rootLayer && l.id === rootLayer.id) return;
    layerNode[l.id] = { id: l.id, type: "@group", name: l.name, x: 0, y: 0, w: 0, h: 0, children: [], visibility: l.state === "show" ? void 0 : l.state };
  });
  var containerOf = function(layerId) {
    return layerId && layerNode[layerId] ? layerNode[layerId] : null;
  };
  var root = [];
  var placedLayers = {};
  var placeLayer = function(layerId) {
    if (!layerNode[layerId] || placedLayers[layerId]) return;
    placedLayers[layerId] = true;
    var parentLayer = layerById[layerId].parentId;
    if (parentLayer && layerNode[parentLayer]) placeLayer(parentLayer);
    var parent = containerOf(parentLayer);
    (parent ? parent.children : root).push(layerNode[layerId]);
  };
  flat.forEach(function(c) {
    var layerId = c.type === "@group" && c.layerId !== void 0 ? c.layerId : effLayer(c);
    delete c.layerId;
    placeLayer(layerId);
    var parent = containerOf(layerId);
    (parent ? parent.children : root).push(c);
  });
  layers.forEach(function(l) {
    placeLayer(l.id);
  });
  if (rootLayer && rootLayer.state && rootLayer.state !== "show") {
    root.forEach(function(n) {
      if (!layerNode[n.id]) n.visibility = rootLayer.state;
    });
  }
  var fitDeep = function(n) {
    (n.children || []).forEach(fitDeep);
    if (layerNode[n.id]) fitGroup(n);
  };
  root.forEach(fitDeep);
  surface.components = root;
  delete surface.layers;
  delete surface.groups;
  surface.treeVersion = TREE_VERSION;
  return surface;
}

// src/model/index.js
function migrateProject(project) {
  if (!project) return project;
  (project.screens || []).forEach(function(s) {
    migrateSurface(s);
  });
  (project.templates || []).forEach(function(t) {
    migrateSurface(t);
  });
  return project;
}
// Annotate the CommonJS export names for ESM import in node:
0 && (module.exports = {
  CONTAINER_TYPES,
  TREE_VERSION,
  absBox,
  allNodes,
  ancestors,
  childBounds,
  cloneWithNewIds,
  detach,
  effectiveLocked,
  effectiveVisibility,
  find,
  findByName,
  fitGroup,
  insert,
  isAncestor,
  isContainer,
  kids,
  locate,
  migrateProject,
  migrateSurface,
  move,
  parentOf,
  parentSize,
  placeOrphan,
  refitGroupsUp,
  remove,
  unwrap,
  walk,
  wrapInGroup
});
